var sucAgs =

	[

		["102", "AGUASCALIENTES,AGS", "5 DE MAYO ESQ PLAZA PRINCIPAL"],

		["240", "CALVILLO,AGS", "ALLENDE 303 ENTRE JUAREZ Y GOMEZ"],

		["658", "PULGAS PANDAS,AGS", "AGUASCALIENTES NTE.ESQ.INDEPENDENCIA"],

		["727", "JESUS MARIA,AGS", "ALLENDE 101 ESQ EMILIANO ZAPATA"],

		["885", "PLAZA SAN MARCOS,AGS", "AV.DE LA CONV. NTE ESQ. FUND. C.COM."],

		["4014", "CM AGUASCALIENTES CENTRO,AGS", "AV. LOPEZ MATEOS # 214 PTE."],

		["4265", "RIVERO Y GUTIERREZ,AGS.", "5 DE MAYO ESQ RIVERO Y GUTIERREZ"],

		["4371", "CORPORATIVO AGUASCALIENTES", "AV LAS AMERICAS 1603"],

		["4802", "CPAE AGUASCALIENTES,AGS", "AV. AMERICAS 1603"]

	];



var sucBcn = 

	[

		["2", "ENSENADA, B. C. N.", "AV RYERSON Y CALLE 3a No 279"],

		["3", "TIJUANA, B. C. N.", "CALLE 4A Y CONSTITUCION 404"],

		["13", "TECATE, B.C.N.", "JUAREZ # 100 ESQ. ALVARO OBREGON"],

		["78", "SANCHEZ TABOADA MEXICALI", "BLVD.BENITO JUAREZ Y MAGISTERIO"],

		["81", "CENTRO TIJUANA B C N", "CALLE 2a 1935"], 

		["202", "MEXICALI B C N", "LERDO Y ALTAMIRANO 401"],

		["284", "BLVD AGUA CALIENTE TIJUANA", "BLVD.AGUA CALIENTE 4560"],

		["353", "JUAREZ B C N", "AV JUAREZ Y RIVEROL No 520"],

		["385", "JUSTO SIERRA MEXICALI B C N", "JUSTO SIERRA Y CIPRESES 799"],

		["390", "LA MESA B C N", "BLVD.D.ORDAZ Y CJON.TERRAZAS 4002 "],

		["430", "CENTRO CIVICO MEXICALI B C N", "BLVD L.MATEOS Y D L HEROES S/N C.C.C "],

		["440", "REVOLUCION B C N", "AV.REVOLUCION 1764"],

		["471", "ROSARITO B C N", "AV. JUAREZ Y RENE ORTIZ CAMPO S/N "],

		["581", "VALLE MEXICALI", "BLVD LAZARO CARDENAS 1372"],

		["688", "CALAFIA, B.C.N.", "KM 11.5 CARR MEXICALI SN LUIS RIO C "],

		["711", "BLVD.INSURGENTES", "BLVD.INSURGENTES 1200 ESQ.ACCESO LA "],

		["744", "SAN QUINTIN,BCN", "ESQ CAR TRANSP Y RSANCHEZ LC1Y2 L6M1 "],

		["745", "VICENTE GUERRERO B C N", "KM.174 CARRETERA TRANSPENINSULAR "],

		["774", "OTAY (TIJUANA B C N)", "CARRETERA AEROPUERTO 1325 C.C.OTAY "],

		["964", "NUEVA ENSENADA,B.C.N.", "GRAL. ABELARDO L. RODRIGUEZ # 222 "],

		["965", "MISION ENSENADA,B.C.N.", "REFORMA # 1122 EDIF. B 5 Y 6"],

		["966", "VILLAFONTANA MEXICALI,B.C.N.", "BLVD.L.C.RET.MOSCU 1700 C.C.L.51-54 "],

		["967", "VIVA TIJUANA,BCN", "VIA J.\V.AMIS.LARO. C.COM.E.4 L.417 "],

		["968", "PLAYAS DE TIJUANA,BCN", "ENS.130 C.COM.SECC.P.CORONADO L.F-4 "],

		["990", "PARAISO,B.C.N.", "BLVD.DIAZ ORDAZ 4400 C.C.LIMON L 1Y2 "],

		["4018", "CM MEXICALI,BCN", "AV. HEROES Y LIBERTAD # 1000 C.COM. "],

		["4019", "CM TIJUANA PLAZA RIO,BCN", "PASEO DE LOS HEROES # 95-C"],

		["4022", "L OTAY,BCN", "BLVD LAZARO CARDENAS CALZ TECNOLOGIC "],

		["4023", "L INDEPENDENCIA,BCN", "BLVD. F.L.MONTEJANO E INDEP. 209 "],

		["4044", "CM TIJUANA PLAYAS,BCN", "OLAS ALTAS S/N"],

		["4045", "CM TIJUANA PLAZA OTAY,BCN", "CARR. AEROPUERTO # 198"],

		["4046", "G TIJUANA,BCN", "BLVD. LAZARO CARDENAS # 405"],

		["4058", "G ENSENADA,BCN", "CARRETERA TRANSPENINSULAR # 100 "],

		["4060", "G MISION,BCN", "REFORMA # 1122"],

		["4062", "C DORADO,BCN", "CARR. TRANSPENINSULAR # 1292"],

		["4063", "G JUSTO SIERRA,BCN", "FRANCISCO MONTEJANO # 1500"],

		["4064", "G VILLA FONTANA,BCN", "H. COLEGIO MILITAR # 1700"],

		["4065", "L CACHANILLA,BCN", "LOPEZ MATEOS # 1100"],

		["4091", "C SOLER,BCN", "AV. DE LA ALEGRIA # 802"],

		["4109", "L PLAZA PATRIA,BCN", "BLVD. DIAZ Y AV. LAS AMERICAS S/N "],

		["4173", "HIPODROMO,BCN", "HIPODROMO # 19 LOCAL 103-104"],

		["4174", "FUNDADORES,BCN", "BLVD. FUNDADORES # 6637 LOC. 1-2-3 "],

		["4175", "CACHO,BCN", "BLVD.A.CALIENTE 708 Y CARR.ENSENADA "],

		["4176", "BENTON,BCN", "BLVD.D.ORDAZ 7018 LOC. 12-15 Y GDL. "],

		["4177", "CORTEZ,BCN", "CORTEZ S/N ESQ. AV. MEXICO"],

		["4205", "G FLORIDO,BCN", "INSURGENTES # 9802 ESQ. SAUZ"],

		["4206", "G LAS BRISAS,BCN", "BLVD D. ORDAZ 1200-27 Y LAS BRISAS "],

		["4207", "LEY PERIFERICO,BCN", "CALZ M.GOMEZ MORIN ESQ CALZ.INDEPEND "],

		["4208", "SEC SAMSUNG,BCN", "B.LOS OLIVOS 11110 P.IND.FLORID.2aSE "],

		["4209", "G LIBRAMIENTO,BCN", "BLVD INSURGENTES 2120 Y PARQUE LOPEZ "],

		["4210", "G LIBERTAD,BCN", "DEFENSORES DE BC S/N Y CALLETANO "],

		["4245", "L MANDARIN,BCN", "BLVD JUAREZ S/N"],

		["4246", "L PUEBLO AMIGO,BCN", "PASEO DE LOS HEROES S/N"],

		["4296", "L. ENSENADA,BCN", "REFORMA Y ALISIS 1491"],

		["4300", "MARAN,BCN", "UNION Y ELECTRA"],

		["4301", "CETYS,BCN", "GENERAL RAFAEL BUELNA /PERIF. OTE. "],

		["4333", "MATAMOROS,BCN", "L C 4 C COMR MATAM. RUTA INDEP 51034 "],

		["4355", "IMSS MEXICALI,BCN", "CALZ. AVIACION No. 100"],

		["4357", "IMSS TIJUANA,BCN", "BLVD AGUA CALIENTE Y FCO CARDENAS SN "],

		["4358", "IMSS ENSENADA,BCN", "AV BLANCARTE 297 /ALVARADO Y CALLE2A "],

		["4359", "IMSS TECATE,BCN", "AV. JUAREZ No. 280 ORIENTE"],

		["4384", "SEC P.I.M.S.A. BCN", "MERCURIO No. 18 B"],

		["4385", "CIUDAD INDUSTRIAL,BCN", "BLVD INDUSTRIAL LOC 14 PZA GRAZIELLA "],

		["4418", "PACIFICO,BCN", "BLVD. PACIFICO LOTES 1 Y 2 MZA 10 "],

		["4419", "SEC. ROCKWELL,BCN", "IGNACIO LOPEZ RAYON 1699"],

		["4445", "SEC KYUSHU,BCN", "AV. DEL AGUILA AMERICANA 19407"]

	];



var sucBcs =

	[

		["11", "LA PAZ, B.C.S.", "C ESQUERRO 110 ESQ AGUSTIN ARREOLA"], 

		["282", "CIUDAD CONSTITUCION B C S", "AGUSTIN ALECHEA Y FRANCISCO JAVIER M"], 

		["470", "CABO SAN LUCAS B C S", "MIGUEL HIDALGO Y LAZARO CARDENAS"], 

		["473", "GUERRERO NEGRO B C S", "AV. BAJA CALIFORNIA S/N"],

		["545", "PALACIO LA PAZ B C S", "ISABEL LA CATOLICA ESQ BRAVO S/N"], 

		["580", "SAN JOSE DEL CABO,BCS", "BLVD. MIJARES LTE 3 A MZANA 61"],

		["584", "BAHIA DE TORTUGAS B C S", "AV INDEPENDENCIA SUR S/N"],

		["962", "FORJADORES,LA PAZ BCS", "BLVD. FORJADORES 3115 SINALOA Y DGO."], 

		["4247", "ARAM FORJADORES,BCS", "BLVD FORJADORES 2910"],

		["4353", "IMSS LA PAZ,BCS", "BLVD 5 DE FEBRERO ESQ ALTAMIRANO P.A"], 

		["4354", "IMSS CABO SAN LUCAS,BCS", "CARR. A TODOS LOS SANTOS S/N KM 1.5"], 

		["4805", "CPAE LA PAZ,BCS", "CARLOS ESQUERRO 110 ESQ A.ARREOLA"]

	];



var sucCmp = 

	[

		["144", "CIUDAD DEL CARMEN CAMP", "CALLE 31 No 63"], 

		["897", "PLAZA ALAMEDA, CAMP.", "AV. REPUBLICA 2"], 

		["937", "PUERTA DEL MAR CD. DEL CARMEN,CAMP.", "CALLE 31 NO. 180 LOCALES 1 AL 4 "], 

		["4437", "GOBERNADORES,CAMP", "AV. GOBERNADORES 428"], 

		["4526", "CANTARELL,CAMPECHE", "CALLE 33 S/N ESQ. CALLE 52-A"]

	];



var sucChi = 

	[

		["142", "CD. JUAREZ", "AV. 16 DE SEPTIEMBRE"], 

		["155", "CD. DELICIAS,CHIH.", "CALLE 2A NORTE 211"], 

		["172", "CD. CUAUHTEMOC,CHIH.", "AGUSTIN MELGAR # 100 ESQ. HIDALGO "], 

		["251", "MINA", "CALZ SANDERS (CTO COMER SORIANA) "], 

		["352", "SAN FELIPE,CHIH.", "AV. UNIVERSIDAD # 3705"], 

		["647", "CD. CAMARGO,CHIH.", "COMONFORT No 406"], 

		["652", "SENECU,CD. JUAREZ", "MANUEL GOMEZ MORIN 7866"], 

		["830", "PROVINCIAL,CHIH.", "CALLE 26 #2600 ESQ. AV. ZARCO"], 

		["831", "MERCADERES CHIH", "AV GENERAL MACLOVIO HERRERA 71"], 

		["833", "PASO DEL NORTE,CD. JUAREZ", "AVE.TRINFO DE LA REP.3990"], 

		["838", "BOULEVARD ORTIZ MENA,CHIH.", "BLVD A.O.MENA 2819 ESQ. CALIFORNIA "], 

		["843", "PUENTE INTERNACIONAL,CD. JUAREZ", "AVE.TECNOLOGICO /EJERCITO NACIONAL "], 

		["933", "SICOMOROS,CHIH.", "BLVD. ORTIZ MENA 1804"], 

		["4102", "F VALLARTA,CHIH", "AV. VALLARTA ESQ. AV. ZARAGOZA S/N "], 

		["4103", "F LEONES,CHIH", "BLVD A.ORTIZ MENA S/N ESQ CARBONEL "], 

		["4104", "F UNIVERSIDAD,CHIH", "AV UNIVERSIDAD S/N ESQ.DIV.DEL NORTE "], 

		["4122", "BG CHIHUAHUA LA SIERRA,CHIH", "AV ZARCO S/N ESQ. PRESA CHUVISCAR "], 

		["4123", "BG CHIHUAHUA AMERICAS,CHIH", "AV AMERICAS SN ESQ.BLVD A.ORTIZ MENA "], 

		["4132", "F RIO GRANDE,CHIH.", "LOPEZ MATEOS Y VICENTE GUERRERO "], 

		["4134", "DELPHI RIO BRAVO VII,CHIH", "AV. PRINCIPAL S/N"], 

		["4139", "F TECNOLOGICO,CHIH", "TECNOLOGICO ESQ. PEDRO ROSALES"], 

		["4141", "F CUAUHTEMOC,CHIH", "AV 16 DE SEPTIEMBRE ESQ. M. ESCOBEDO "], 

		["4158", "S SAN LORENZO", "FRAY PEDRO DE GANTE # 5299 Y TRIUNFO "], 

		["4159", "S PLAZA JUAREZ", "TEC. Y EJERCITO NACIONAL # 2701 "], 

		["4193", "CARR CHIHUAHUA", "PERIF. DE LA JUVENTUD 6300 Y F.VILLA "], 

		["4232", "PLAZA VALLARTA,CHIH.", "AV. ZARAGOZA 1114 LOC. 2"], 

		["4273", "ANAHUAC,CHIH.", "DOMIC.CONOCIDO S/N D/C EMP.PONDERCEL "], 

		["4294", "SEC MOTOROLA,CHIH.", "KM 15.5 CARR A CD JUAREZ"], 

		["4305", "TRW DE CHIHUAHUA,CHIH", "MIGUEL DE CERVANTES # 141"], 

		["4425", "&quot;F. ALSUPER NUEVA ESPA&Ntilde;A,CHIH&quot;", "BLVD FUENTES MAREZ 8600 ESQ.NVA.ESPA "], 

		["4426", "CARR EJERCITO NACIONAL,CHIH", "AV. EJERCITO NACIONAL No. 5230"], 

		["4476", "HENEQUEN,CHIH", "AV DE LAS TORRES 410 ENT.VALLE.CIROS "], 

		["4481", "SHAKESPEARE,CHIH", "SHAKESPEARE L2 M14 ENT.M.CERVA/RUDYA "], 

		["4492", "AEROPUERTO JUAREZ,CHIH", "AV. TECNOLOGICO 6450-B"], 

		["4493", "AZTECAS JUAREZ,CHIH", "EJE VIA JUAN GABRIEL Y C.DE L.ANDES "], 

		["4497", "SEC FORD COCLISA,CHIH", "AV DEL CHORRO 1751 ENTRE RIVERENO "]

	];



var sucChp = 

	[

		["5", "VENUSTIANO CARRANZA, CHIS.", "1a PONIENTE AV. CENTRAL # 11"], 

		["50", "OCOSINGO, CHIS.", "AV CENTRAL JUAREZ 3"], 

		["46", "TERAN, CHIS.", "BLVD DR BELISARIO DOMINGUEZ 3187 "], 

		["61", "OCOZOCUAUTLA, CHIS.", "AV SUR ESQ CALLE CENTRAL No 4"], 

		["73", "VILLA LAS ROSAS,CHIS", "CENTRAL 8"], 

		["130", "TAPACHULA CHIS", "CENTRAL NORTE No. 9"], 

		["226", "HUIXTLA,CHIS.", "CENTRAL NORTE # 12-1"], 

		["252", "ARRIAGA CHIS", "2a AV ORIENTE No 3"], 

		["273", "COMITAN CHIS", "CENTRAL ROSARIO CASTELLANOS SUR # 10 "], 

		["296", "VILLAFLORES CHIS", "CENTRAL # 25"], 

		["324", "TONALA CHIS", "AV. HIDALGO 137"], 

		["360", "PIJIJIAPAN,CHIS", "2A. AV. NORTE S/N ESQ. 1A CALLE PTE. "], 

		["386", "SAN CRISTOBAL LAS CASAS CHIS", "PLAZA 31 DE MARZO Y REAL DE GUADALUP "], 

		["488", "CINTALAPA CHIS", "CENTRAL Y 1A NORTE # 13"], 

		["596", "BONAMPAK,CHIS.", "BLVD. BELISARIO DOMINGUEZ # 1550 "], 

		["743", "FRONTERA COMALAPA,CHIS", "AV. CENTRAL S/N ESQ. CALLE CENTRAL "], 

		["788", "YAJALON,CHIS", "1A. AV. SUR ESQ. 1A. CALLE PONIENTE "], 

		["4099", "ANGEL ALBINO CORZO,CHIS", "BLVD. ANGEL ALBINO CORSO # 2862-A "], 

		["4100", "PLAZA SAN DIEGO,CHIS", "BLVD. JUAN SABINES KM. 1170"], 

		["4129", "BG TUXTLA SOL,CHIS", "QUINTA AV. NTE. PTE. # 2650"], 

		["4196", "PUERTO MADERO,CHIS.", "4TA. AV. SUR 167 LOC. H Y LOC. I "], 

		["4261", "ELECTRICISTA,CHIS.", "5a Av PTE 2650 LOC-1 C.C.TUXTLA SOL "], 

		["4283", "SEC. REFORMA,CHIS", "CARR. JUAREZ CHIAPAS"], 

		["4397", "IMSS TAPACHULA,CHIS", "CARR. COSTERA Y ANILLO PERIFERICO SN "], 

		["4398", "IMSS TUXTLA,CHIS", "1A. AV. NORTE ORIENTE 353"], 

		["4412", "CHIAPA DE CORZO,CHIS", "BLVD PZA ANGEL ALBINO CORZO No. 103 "], 

		["4451", "SAN ROQUE,CHIS", "9a. AV. SUR ORIENTE No. 780"], 

		["4452", "BALUN CANAN,CHIS", "CARRETERA INTERNACIONAL S/N KM 1250 "], 

		["4457", "SAN AGUSTIN,CHIS", "OCTAVA AVENIDA NORTE No. 46"]

	];



var sucCoa = 

	[

		["85", "PERIFERICO COAH", "PRIF. LUIS ECHEVERRIA Y MONCLOVA"], 

		["98", "AVENIDA JUAREZ", "JUAREZ Y CALLE 29"], 

		["124", "SALTILLO,COAH", "ALLENDE ESQ OCAMPO"], 

		["132", "TORREON COAH", "HIDALGO ESQ VALDES CARRILLO"], 

		["181", "SAN PEDRO DE LAS COLONIAS COAH", "JUAREZ OTE 228"], 

		["271", "CD. ACU&Ntilde;A,COAH.", "GUERRRO # 426"], 

		["382", "TORREON ALAMEDA COAH", "AV HIDALGO ESQ GARCIA CARRILLO"], 

		["438", "NUEVA ROSITA COAH", "ADOLFO LOPEZ MATEOS No 1227"], 

		["551", "BOULEVARD MONCLOVA COAH", "BLVD HAROLD R PAPE 501 LOC C Y D"], 

		["716", "NAVA COAH", "V CARRANZA ESQ BENITO JUAREZ"], 

		["723", "PARRAS DE LA FUENTE,COAH.", "16 DE SEPTIEMBRE # 24 LOC. 1 Y 2"], 

		["872", "PRESIDENTE CARDENAS COAHUILA", "PERIF. L. ECHEVERRIA ESQ. ARTEAGA"], 

		["952", "OBELISCO,COAH.", "NAZARIO ORTIZ GARZA # 2550"], 

		["4147", "LA ROSITA,COAH", "SALTILLO 400 # 650"], 

		["4156", "S ORIENTE,COAH", "BLVD. TORREON MATAMOROS # 5000"], 

		["4157", "S REVOLUCION,COAH", "BLVD. REV. Y CALZADA SALTILLO 400"], 

		["4250", "G ABASALO,COAH.", "ABASOLO Y PERIFERICO LUIS ECHEVERRIA"], 

		["4304", "S FUENTES,COAH.", "DIAG.DE LAS FUENTES /PASEO DE LA R."], 

		["4306", "GENERAL MOTORS SALTILLO,COAH", "CARR SALTILLO/MTY. KM 7.5"], 

		["4373", "BOULEVARD CONSTITUCION", "BLVD. CONSTITUCION 1304, OTE"], 

		["4374", "S INDEPENDENCIA,COAH", "BLVD. INDEPENDENCIA 1100, OTE"], 

		["4401", "CARR. SALTILLO,COAH", "PERIFERICO LUIS ECHEVERRIA 6301 LOC8"], 

		["4421", "S. COSS,COAH", "BLVD. FRANCISCO COSS S/N LOCAL 1-C"], 

		["4423", "TULIPANES,COAH", "BLVD. CARR. A LOS GONZALEZ 1095"], 

		["4484", "LOURDES,COAH", "BLVD PERIF.L.ECHEVERRIA S/N LOTE 3Y4"], 

		["4808", "BOULEVAR 57,COAH", "LAZARO CARDENAS 2123"]

	];



var sucCol = 

	[

		["187", "MANZANILLO COL", "MEXICO 136"], 

		["203", "PLAZA SAN FERNANDO,COL.", "CONSTITUCION # 555 LOC. 13"], 

		["852", "GALVAN,COL", "CALZ. GALVAN # 215 LOC. 1 P. B. "], 

		["944", "PLAYA SALAHUA,COL", "BLVD. MIGUEL DE LA MADRID KM. 11.5 "], 

		["4111", "L COLIMAN,COL", "CARR. COLIMA-XOQUIMATLAN # 501"]

	];



var sucDf = 

	[

		["65", "PLAZA ORIENTE,D.F.", "AV.CANAL DE TEZONTLE 1520 LOCS.B1 B2"], 

		["100", "OFICINA CENTRAL D.F..", "ISABEL LA CATOLICA 44"], 

		["105", "CINCO DE MAYO D F", "MADERO 21"], 

		["115", "MERCED D F", "VENUSTIANO CARRANZA 145"], 

		["125", "SAN COSME D F", "RIBERA DE SAN COSME # 11"], 

		["128", "SANTO DOMINGO D F", "LEANDRO VALLE 4"], 

		["141", "TACUBAYA D F", "AV JALISCO 160"], 

		["149", "PERALVILLO D F", "JESUS CARRANZA 129"], 

		["160", "MESONES D F", "AV 20 DE NOVIEMBRE 134"], 

		["185", "TACUBA D F", "CALZ MEXICO TACUBA 737"], 

		["189", "NONOALCO D F", "DR. ATL. # 290"], 

		["194", "SANTA BARBARA D F", "LAGO ALBERTO # 446 P.B."], 

		["196", "SAN ANTONIO ABAD D F", "CALZ. SAN ANTONIO ABAD # 178"], 

		["199", "INSURGENTES LIVERPOOL D F", "INSURGENTES SUR 107 ESQ LIVERPOOL"], 

		["205", "COYOACAN D F", "AV FELIX CUEVAS 610"], 

		["207", "SAN PABLO D F", "ANILLO DE CIRCUNVALACION 912"], 

		["208", "LA VILLA D F", "CALZ DE GUADALUPE 407-A"], 

		["209", "INSURGENTES COAHUILA D F", "INSURGENTES SUR 368"], 

		["212", "AEROPUERTO D F", "BLVD PUERTO AEREO 342 ESQ NORTE 29"], 

		["221", "COLON D F", "DONATO GUERRA 28 ESQ PASEO D REFORMA"], 

		["224", "SAN RAFAEL D F", "MANUEL MA CONTRERAS 133"], 

		["227", "MIXCOAC D F", "AV REVOLUCION 1004"], 

		["234", "PORTALES D F", "CALZ DE TLALPAN 1280"], 

		["236", "NARVARTE D F", "DIAGONAL SAN ANTONIO 1309"], 

		["241", "TLALPAN SAN FERNANDO D F", "CALZ DE TLALPAN 4791 ESQ SN FERNANDO"], 

		["242", "VALLADOLID OAXACA,D.F.", "OAXACA 108"], 

		["244", "DOCTORES D F", "DR.BALMIS 222 ESQ.AV CUAUHTEMOC"], 

		["245", "CUITLAHUAC D F", "AV. CUITLAHUAC 3423"], 

		["246", "AZCAPOTZALCO, D F", "JARDIN HIDALGO 2"], 

		["259", "JAMAICA,D.F.", "MORELOS 13 ESQ. CONGRESO DE LA UNION"], 

		["260", "GUERRERO D F", "GUERRERO # 18 P.B."], 

		["261", "EJERCITO NACIONAL,DF", "EJERCITO NACIONAL 966"], 

		["266", "INSURGENTES STA MARGARITA D F", "INSURGENTES SUR 926"], 

		["268", "INSURGENTES FELIX CUEVAS D F", "AV FELIX CUEVAS 101 ESQ OSO"], 

		["269", "VIGA ERMITA D F", "CALZ LA VIGA 1805"], 

		["270", "SAN ANGEL D F", "AV REVOLUCION 1861"], 

		["283", "COLONIA DEL VALLE D F", "AV. COLONIA DEL VALLE # 732 P.B."], 

		["287", "TLATELOLCO D F", "MANUEL GONZALEZ 139"], 

		["298", "DIVISION DEL NORTE TLALPAN D F", "DIVISION DEL NORTE 3695"], 

		["321", "PILARES D F", "PILARES # 541 P.B."], 

		["322", "NUEVA MIXCALCO D F", "VIDAL ALCOCER # 11 P.B."], 

		["333", "JARDIN BALBUENA D F", "FRAY SERVANDO TERESA DE MIER # 979"], 

		["344", "XOCHIMILCO D F", "AV PROLONGACION DIV DEL NTE 5441"], 

		["346", "COPILCO UNIVERSIDAD D F", "UNIVERSIDAD 1731"], 

		["369", "INGUARAN, D.F.", "AV OTE 107 No 3118 ESQ C DE LA UNION"], 

		["370", "ARAGON VILLA GPE.,DF", "FF CC HIDALGO 1414"], 

		["375", "ARCOS DE BELEM D F", "BALDERAS 144"], 

		["377", "LOMAS BARRILACO D F", "AV DE LAS PALMAS 751"], 

		["378", "CENTRO SCOP D F", "AV LAZARO CARDENAS 574 ESQ BLVD XOLA"], 

		["379", "NI&amp;O PERDIDO D F", "MANUEL M. FLORES 3 ESQ. L. CARDENAS"], 

		["384", "MARIANO ESCOBEDO D F", "MARIANO ESCOBEDO 425"], 

		["404", "AGRICOLA ORIENTAL D F", "CALZ IGNACIO ZARAGOZA 885"], 

		["412", "TIBER D F", "RIO TIBER # 67 P.B."], 

		["414", "COYUYA D F", "AV COYUYA 224"], 

		["419", "TLALPAN CIRCUNVALACION D F", "CALZ DE TLALPAN 2141"], 

		["457", "CD. NEZAHUALCOYOTL, D.F.", "CALZ I ZARAGOZA 1874 ESQ GABRIEL LEY"], 

		["491", "TERMINAL DEL NORTE D F", "AV DE LOS 100 METROS 4907 LOCAL 10"], 

		["504", "MILPA ALTA D F", "CALLE CONSTITUCION 13 MILPA ALTA"], 

		["507", "INSURGENTES FLORIDA D F", "AV INSURGENTES SUR 1548 ESQ FEBO"], 

		["508", "SAN LORENZO TEZONCO D F", "TLAHUAC # 4631"], 

		["509", "OFICINA MATRIZ MEZZANINE D F", "I. LA CATOLICA # 44 P.B."], 

		["514", "TERMINAL ORIENTE D F", "IGNACIO ZARAGOZA # 73"], 

		["515", "SAN JERONIMO D F", "AV SAN JERONIMO 630"], 

		["516", "LAS AGUILAS,DF", "CALZ. DE LOS LEONES # 247"], 

		["517", "LOS ANGELES,D.F.", "ERMITA IZTAPALAPA 1863"], 

		["525", "PLAZA BOSQUES D F", "C.COM. BOSQUES DURAZNO 187 L.15 Y 16"], 

		["532", "TLAHUAC D F", "TLAHUAC # 185 P.B."], 

		["534", "LOMAS DE VISTA HERMOSA D F", "JOSE M. CASTORENA # 3111 ESQ.SN JOSE"], 

		["541", "PERISUR D F", "PERISUR E INS LOC 118 AL 126 SEC. B"], 

		["563", "ALBERCA OLIMPICA D F", "DIVISION DEL NORTE 2350"], 

		["571", "ASTURIAS,DF", "CALZADA CHABACANO # 43"], 

		["575", "NAPOLES D F", "MONTECITO 38 LOCAL 1"], 

		["577", "MIRAMONTES D F", "C DE MIRAMONTES 2784 ESQ AGAPANDO"], 

		["586", "EDUARDO MOLINA,DF", "EDUARDO MOLINA # 1623 Y OTE. 157"], 

		["592", "OLIVAR DE LOS PADRES,DF", "AVENIDA DE LAS TORRES 446"], 

		["595", "MOCTEZUMA,DF", "IGNACIO ZARAGOZA # 270"], 

		["613", "CIRUELOS,D.F.", "CANAL DE MIRAMONTES # 2600"], 

		["637", "ABASTOS IZTAPALAPA,D.F.", "CENTRAL DE ABASTOS SECTOR A/B EJE 2"], 

		["638", "MISTERIOS,DF", "CALZ.DE GUADALUPE 192"], 

		["649", "GALERIAS D F", "MELCHOR OCAMPO # 193 P.B."], 

		["654", "NIZA,D.F.", "NIZA # 66 P.B."], 

		["660", "LILAS,D.F.", "PASEO DE LAS LILAS 92 LOC 148-152"], 

		["661", "PLAZA CONDESA,DF", "AV.NUEVO LEON 67 CONDOMINIO PLZA CON"], 

		["662", "TENAYUCA,DF", "AV DE LA VENTISCA 100"], 

		["675", "LOS SAUCES,D.F.", "CALZ. DEL HUESO # 670"], 

		["681", "FUENTES BROTANTES D F", "AV INSURGENTES SUR 3976"], 

		["689", "EUGENIA,D.F.", "EUGENIA # 901 ESQ. GABRIEL MANCERA"], 

		["690", "PERIFERICO SANTA TERESA D F", "CAMINO A STA TERESA No 1508"], 

		["698", "BASILICA,DF", "INSURGENTES NORTE # 1788"], 

		["701", "CAMPESTRE CHURUBUSCO,D.F.", "TAXQUE&Ntilde;A # 1565"], 

		["739", "CM PABELLON BOSQUES,DF", "PROLONGACION BOSQUES DE REFORMA 1813"], 

		["746", "PATRIOTISMO HOLBEIN,DF", "AV PATRIOTISMO 671 LOCAL 2"], 

		["750", "SANTA FE,DF", "VASCO DE Q.3800 L-180 CTO.COM.STA FE"], 

		["825", "EL RETO&Ntilde;O,D.F.", "CALZ. DE LA VIGA # 1381"], 

		["844", "REFORMA RIO RIN D F", "PASEO DE LA REFORMA 243 P B"], 

		["856", "HORACIO,DF", "HORACIO 411 P.B. Y MEZZANINE"], 

		["862", "CENTRO DE SERVS BANCARIOS PALMA D F", "PALMA 44"], 

		["873", "SERVICIOS BANCARIOS AL PERSONAL,DF", "PALMA 42 P B"], 

		["947", "FLORENCIA D.F.", "FLORENCIA 53"], 

		["948", "CAMARONES,DF", "CUITLAHUAC # 3305"], 

		["956", "GALERIAS COAPA,DF", "AV CANAL MIRAMONTES 3197 C.COM.COAPA"], 

		["957", "PEDREGAL DEL SUR,DF", "PERIF.SUR 5272 C.COM.PATIO PEDREGAL"], 

		["958", "PLAZA COYOACAN,DF", "COYOACAN #2000 CTO.COM.CTO.COY.L.413"], 

		["959", "PLAZA HIDALGO,DF", "CALLE AGUAYO # 3"], 

		["970", "MOLIERE,DF", "AV.EJERCITO NACIONAL # 769"], 

		["975", "MUNICIPIO LIBRE, D.F.", "MUNICIPIO LIBRE # 314"], 

		["978", "ROSARIO,D.F.", "AQUILES SERDAN # 1314"], 

		["983", "SCHILLER, D.F.", "AV. EJERCITO NACIONAL No. 350"], 

		["989", "ADUANA AEROPUERTO D.F.", "AV 602 S/N EDIFICIO DE LA ADMON."], 

		["991", "SAN ANTONIO,D.F.", "MIGUEL ANGEL 170"], 

		["992", "CHURUBUSCO,D.F.", "CALZ. DE TLALPAN # 2050"], 

		["994", "PANTITLAN,D.F.", "CALLE 6 # 306-B ESQ. AV. XOCHIMILCO"], 

		["4004", "CM ZARAGOZA,DF", "IGNACIO ZARAGOZA # 1450"], 

		["4008", "CM LA VILLA,DF", "PROL. CZDA. DE LOS MISTERIOS # 62"], 

		["4009", "CM TACUBA,DF", "CALZ. MEXICO TACUBA # 911"], 

		["4030", "G TACUBAYA,DF", "JOSE MORAN # 3"], 

		["4049", "CM EL DORADO,MEX PENDIENTE", "LAGO VICTORIA 74"], 

		["4050", "CM VILLA COAPA,DF", "CALZADA DEL HUESO # 530"], 

		["4051", "CMB CENTRO,DF", "VENUSTIANO CARRANZA # 125"], 

		["4082", "SANTA CRUZ MEYEHUALCO,DF", "ERMITA IZTAPALAPA # 2680"], 

		["4083", "CULHUACAN TAXQUE&Ntilde;A,DF", "TAXQUE&Ntilde;A # 2167 LOCAL D"], 

		["4084", "UNIDAD INDEPENDENCIA,DF", "SAN BERNABE # 327"], 

		["4085", "AXOMIATLA,DF", "LAS AGUILAS # 1952 LOC 18-19 Y 20"], 

		["4086", "FORTIN CHIMALISTAC,DF", "UNIVERSIDAD # 2013"], 

		["4087", "AZTECAS,DF", "AZTECAS # 270 LOC. 69 AL 72"], 

		["4088", "SAN JUAN DE ARAGON,DF", "JOSE LORETO FABELA # 55 LOC. 5 AL 12"], 

		["4135", "A. CANTIL,D.F.", "AZTECAS 270 ENTRE MOCTEZUMA Y PANTEO"], 

		["4142", "MEC FORD,DF", "REFORMA # 333"], 

		["4144", "PASEO DE LAURELES,DF", "REF. # 1813 C.C. P.BOSQUES LOC 114"], 

		["4145", "INSURGENTES NUEVO LEON,DF", "INSURGENTES SUR # 527 P.B. LOC. A-B"], 

		["4146", "CAMPOS ELISEOS,DF", "GALILEO # 8 ESQ. ARISTOTELES # 9"], 

		["4152", "TORRES LINDAVISTA,DF", "C.COM.TORRES LINDAVISTA LOC.2-5 I. F"], 

		["4166", "BA ACUEDUCTO DE GUADALUPE,DF", "ING. LUIS ESPINOZA 170 ENTRE PALOMAS"], 

		["4183", "SINATEL,DF", "SUR 73 # 203"], 

		["4184", "NATIVITAS TLALPAN,DF", "LAGO PONIENTE # 20"], 

		["4186", "SEC FULLER TEPEPAN,DF", "FCO. VILLA 5 ESQ. SAN LAZARO"], 

		["4187", "SEC FULLER XOCHIMILCO,DF", "REDENCION 17 /SAN MARCOS Y D DEL NTE"], 

		["4188", "SEC GENERAL MOTORS,DF", "L. VICTORIA 74 / EJERCITO Y C. SAAV."], 

		["4189", "SEC PEMEX,DF", "EJERCITO N. # 216 LEIBITZ/LAPLACE"], 

		["4190", "SEC KIMBERLY CLARK,DF", "LAGRANGE 103 ENTRE HOMERO Y E. NAL."], 

		["4204", "SEC HOECHST MARION ROUSSEL,DF", "UNIVERSIDAD # 1738 Y M.A. DE QUEVEDO"], 

		["4222", "SEC NACIONAL PROVINCIAL,DF", "AV. DE LAS TORRES # 395"], 

		["4224", "SEC PEMEX TORRE EJECUTIVA,DF", "MARINA NACIONAL 329 MEZZANINE"], 

		["4225", "SEC PALACIO LEGISLATIVO,DF", "CONGRESO DE LA UNION"], 

		["4233", "LAGUNILLA,DF", "ALLENDE # 87 LOC. I,J,K"], 

		["4254", "SEC U IBEROAMERICANA,DF", "PROL. REFORMA # 880 CORALES Y CANT."], 

		["4255", "SEC FEDERAL EXPRESS,DF", "V. DE QUIROGA 2999 P.1 Y CALLE A Y B"], 

		["4259", "SEC LOREAL,DF", "OKLAHOMA # 14"], 

		["4266", "ROMA OBREGON,DF", "ALVARO OBREGON # 168 ESQ. TONALA"], 

		["4272", "PARQUE REFINERIA,DF", "NEXTENGO # 78 C.C.AZCAP.LOC 12 AL 15"], 

		["4293", "VICTORIA,DF", "DOLORES # 41 LOC. B-C"], 

		["4299", "SEC PEMEX CORPORATIVO,DF", "M. NACIONAL 329 /B.HIPOLITO Y MAYRAN"], 

		["4312", "PROMECO,DF", "MAIZ # 49/REDENCION Y 16 DE SEP."], 

		["4337", "CORPORATIVO SANTA FE,DF", "ACTUARIO ROBERTO MEDELLIN 800 P.B."], 

		["4338", "SEC. EMBAJADA E.U.A.,DF", "AV. REFORMA No. 305"], 

		["4339", "IMSS SAN ANGEL,DF", "PLAZA SAN JACINTO No 22"], 

		["4340", "IMSS DEL VALLE,DF", "AV. COYOACAN No 1540"], 

		["4341", "IMSS PIEDAD NARVARTE,DF", "AV. CUAUHTEMOC 451"], 

		["4342", "IMSS SANTA ANITA,DF", "PLUTARCO ELIAS CALLES 579"], 

		["4343", "IMSS CHURUBUSCO,DF", "RIO CHURUBUSCO 609"], 

		["4348", "SAN FELIPE,DF", "EJIDO S/N LT 45 MZ 5"], 

		["4350", "SANTA ROSA,D.F.", "CALZ VALLEJO #1736 MZA 15 LT 32 L1-4"], 

		["4370", "OLIVAR DEL CONDE,DF", "AV SANTA LUCIA 810 LOCALES 15 Y 16"], 

		["4402", "CHINAMPAS,DF", "PINO No. 60"], 

		["4406", "B.A. OBSERVATORIO,D.F.", "AV. OBSERVATORIO 457"], 

		["4407", "A. ECHEGARAY,DF", "EMILIANO ZAPATA 7 ENT.CUAUHTEMOC Y C"], 

		["4409", "BOSQUES DE MINAS,D.F.", "BOSQUES DE MINAS No.25 LOCAL 10"], 

		["4431", "MAGDALENA CONTRERAS,DF", "AV. ALVARO OBREGON 1385 LOCAL 3 Y 4"], 

		["4432", "SAN PEDRO MARTIR,DF", "CINCO DE MAYO 190 ENT.CAR.FED.CUERNA"], 

		["4453", "AUCHAN COYOACAN,DF", "MIGUEL ANGEL DE QUEVEDO 443"], 

		["4462", "PICACHO SANTA TERESA,D.F.", "PERIFERICO SUR 4020 L4Y5 CC P.STA TE"], 

		["4470", "A. PLATEROS,DF", "BLVD.ADOLFO L.MATEOS 1701 ENT.MOLINO"], 

		["4501", "A LAS AGUILAS,D.F.", "CALZ DE LAS AGUILAS 820 ENT.O FARRIL"], 

		["4504", "TELETON ESTADIO AZTECA", "CALZADA DE TLALPAN 3465"], 

		["4505", "TELETON ESTADIO AZTECA II", "CALZADA DE TLALPAN 3465"], 

		["4506", "TELETON TELEVISA SAN ANGEL", "BLVD ADOLFO LOPEZ MATEOS 232"], 

		["4515", "SALA B AEROPUERTO,DF", "AEROPUERTO INTERNAL SALA B LOCAL 39"], 

		["4518", "LEGARIA,D.F.", "CALZADA LEGARIA 252"], 

		["4524", "TIENDA UNAM,DF", "DALIAS S/N"], 

		["4530", "3M DE MEXICO,DF", "AV. SANTA FE 55"]

	];



var sucDur = 

	[

		["60", "GUERRERO,DGO", "HIDALGO ESQ FCO. SARABIA"], 

		["156", "GOMEZ PALACIO DGO", "JUAREZ ESQ AV VICTORIA"], 

		["374", "CANATLAN DGO", "ALDAMA Y GUERRERO"], 

		["489", "TEPEHUANES,DGO", "GRAL. EDUARDO ARRIETA ESQ. PATONI"], 

		["497", "20 DE NOVIEMBRE DGO", "20 DE NOV. Y HEROICO COLEGIO MILITAR"], 

		["4148", "GONZALEZ DE LA VEGA,DGO.", "BLVD.M.ALEMAN Y BLVD. GLZ.DE LA VEGA"], 

		["4155", "S JARDINES", "MAGNOLIAS # 100"], 

		["4257", "S LAS ROSAS,DGO", "BLVD.M.ALEMAN Y CZDA J.AGUSTIN C."], 

		["4315", "GUADIANA,DGO", "BLVD DOMINGO ARRIETA ESQ FCO GLZ."], 

		["4325", "G REAL DEL PRADO,DGO", "FRANCISCO DE IBARRA 1100 OTE."], 

		["4483", "BOULEVARD VILLA,DGO", "BLVD FRANCISCO VILLA 1014"]

	];



var sucEdomex = 

	[

		["16", "TENANCINGO,EDO MEX", "PZA MORELOS PTE ESQ PABLO G CASANOVA"], 

		["26", "COATEPEC DE HARINAS,EDO MEX", "PLAZA HIDALGO 10"], 

		["36", "ALMOLOYA DE JUAREZ,EDO MEX", "HIDALGO 1 LOCAL B"], 

		["39", "TEMOAYA,EDO MEX", "PORTAL AYUNTAMIENTO 101"], 

		["59", "TEJUPILCO,MEX", "VICENTE GUERRERO No. 5"], 

		["92", "LAS FLORES,EDO MEX", "BLVD. ALFREDO DEL MAZO 705 LOCAL 15"], 

		["131", "TOLUCA,EDO MEX", "HIDALGO ESQ. GALEANA 223"], 

		["243", "CUAUTITLAN EDO DE MEX", "CALZ DE GUADALUPE 101"], 

		["258", "TEXCOCO EDO DE MEX", "NEZAHUALCOYOTL 208 TEXCOCO"], 

		["285", "LEANDRO VALLE,EDO MEX", "INDEPENDENCIA OTE 1201 ESQ LEANDRO V"], 

		["326", "CUATRO CAMINOS EDO DE MEX", "AV 1o DE MAYO 236"], 

		["347", "PLAZA SATELITE EDO DE MEX", "CTO.PZA.SATELITE SECC A LOC 20 AL 26"], 

		["371", "VIVEROS DE LA LOMA, D.F.", "VIA DR GUSTAVO BAZ 299"], 

		["403", "ECATEPEC EDO DE MEX", "AV NACIONAL 58 KM 22 1/2 CARRETERA"], 

		["482", "TECAMACHALCO EDO DE MEX", "AV. DE LAS FUENTES No. 46 P.B."], 

		["502", "ECHEGARAY ALCE BLANCO EDO DE MEX", "PASEO DE LA FLORIDA # 1605 P.B."], 

		["503", "CHINCONCUAC,EDO.MEX.", "HIDALGO 17"], 

		["505", "CUAUTITLAN IZCALLI EDO DE MEX", "ANDADOR Y TEMUAYA 34"], 

		["506", "ZUMPANGO EDO DE MEX", "GANTE 9"], 

		["512", "IXTAPALUCA,EDO.MEX.", "MUNICIPIO LIBRE 16 Y CENTENARIO"], 

		["513", "NEZA CENTRO EDO DE MEX", "AV LOPEZ MATEOS 583"], 

		["520", "PASEO COLON,EDO MEX", "PASEO COLON 215"], 

		["521", "LOMAS VERDES EDO DE MEX", "ALAMO PLATEADO No 1"], 

		["522", "CENTRO URBANO CUAUTITLAN IZCALLI,MEX", "AV.TEOTIHUACAN MANZ C 24-B"], 

		["523", "PRADO VALLEJO,EDO MEX", "CALZ VALLEJO 1110 (EJE 1 PONIENTE)"], 

		["524", "VILLA NICOLAS ROMERO MEX", "AV. 20 DE NOVIEMBRE 3 P.B."], 

		["527", "CHALCO EDO. DE MEX.", "AV. HIDALGO No. 12, ESQ. MATAMOROS"], 

		["528", "SAN JUAN TEOTIHUACAN MEX", "AV. V. GUERRERO ESQ. I. ALLENDE"], 

		["531", "LOS REYES LA PAZ EDO DE MEX", "CARR FED A PUEBLA KM 18 1/2 MORELOS"], 

		["536", "TULTITLAN EDO DE MEX", "AV. SAN ANTONIO 1 P.B."], 

		["537", "TOLLOCAN,EDO MEX", "PASEO TOLLOCAN 721"], 

		["538", "NEZA SOR JUANA EDO DE MEX", "AV SOR JUANA I DE LA CRUZ 100 2a SEC"], 

		["539", "CERRO GORDO EDO DE MEX", "VIA MORELOS ESQ. SANTA CLARA P.B."], 

		["572", "LA HERRADURA EDO DE MEX", "BOSQUES DE MOCTEZUMA 1 LOC 8 9 Y 10"], 

		["573", "SATELITE PONIENTE EDO DE MEX", "CIRCUNVALACION PTE. 146 LOCAL 10"], 

		["574", "INDUSTRIAL XALOSTOC MEX", "EMILIANO ZAPATA 63 ESQ BENITO JUAREZ"], 

		["587", "ACAMBAY,EDO MEX", "JORGE JIMENEZ CANTU 19"], 

		["588", "METEPEC,EDO MEX", "PINO SUAREZ SUR 2400 ESQ.AV.AJUSCO"], 

		["615", "CIRCUITOS NEZA,MEX", "CIRCUITO 1 ESQ. PAGARE"], 

		["617", "PZA. ARAGON,EDO. DE MEX.", "HANK GLZ. 120 L.29,50 C.C.PZA.ARAGON"], 

		["627", "ATIZAPAN EDO DE MEX", "BLVD. ADOLFO LOPEZ MATEOS 56 P.B."], 

		["633", "CENTRO ADMINISTRATIVO TLALNEPANTLA,MEX", "AV HIDALGO 92 LA ROMANA"], 

		["651", "CENTRO ADMINISTRATIVO NAUCALPAN EDO DE M", "MEXICAS 39 SANTA CRUZ ACATLAN"], 

		["755", "LAS PLAZAS,MEX", "LOMAS VERDES # 750"], 

		["765", "JILOTEPEC,MEX", "VICENTE GUERRERO 307"], 

		["777", "SANTIAGO TIANGUISTENGO, MEX", "GOMEZ FARIAS ESQ. PORTAL DEL BUEN S."], 

		["798", "VALLE DE BRAVO,EDO MEX", "16 DE SEPTIEMBRE P.B. ESQ. BENITO J."], 

		["799", "SAN MATEO ATENCO,EDO MEX", "AV JUAREZ 113"], 

		["824", "ATLACOMULCO,EDO MEX", "ISIDRO FABELA No 36"], 

		["846", "PERINORTE, EDO DE MEX.", "KM.50.5 MEX/QRO.C.C. PTE LOCS.V-2-2"], 

		["855", "INTERLOMAS,MEX", "LOMAS ANAHUAC LOTE 1 MANZ.2 AV.1"], 

		["882", "TONATICO,EDO MEX", "VENUSTIANO CARRANZA S/N ESQ GALEANA"], 

		["892", "COACALCO EDO DE MEX", "AV JOSE LOPEZ PORTILLO KM 27.4"], 

		["916", "TEMASCALTEPEC,EDO MEX", "RIVAPALACIOS 5"], 

		["918", "PLAZA COACALCO EDO. DE MEX.", "AV. J.L.PORTILLO 220-A L.139C L139D"], 

		["946", "CIRCUITOS MEDICOS EDO. DE MEX.", "PAFNUNCIO PADILLA 17"], 

		["960", "BOULEVARES, EDO. DE MEX.", "COLONIA DE LA PAZ 25"], 

		["976", "BOSQUES DE ARAGON,EDO DEMEX.", "AV.H.GLEZ.323 C.C. B.DE A.LOC.75,76"], 

		["981", "VALLE DE CHALCO,EDO. DE MEX.", "TEZOZOMOC S/N"], 

		["986", "VILLAS DE LA HACIENDA, &nbsp; MEX.", "AV.LAGO DE GPE 368 C.C. PLAZA LA HDA"], 

		["4005", "CM LOS REYES,EDO MEX", "SAN FRANCISCO # 88"], 

		["4006", "CM ECATEPEC,EDO MEX", "VIA MORELOS 222"], 

		["4007", "CM IZCALLI,EDO MEX", "JIMENEZ CANTU S/M"], 

		["4048", "CM VILLAS DE LA HACIENDA, MEX", "LAGO DE GPE. ESQ. DE LAS VILLAS S/N"], 

		["4052", "SEC. ERICSSON,MEX", "VIA DR. GUSTAVO BAZ PRADA 2160"], 

		["4089", "TECAMAC,EDO MEX", "AV. 5 DE MAYO S/N"], 

		["4090", "SANTA MONICA,EDO MEX", "AV. CONVENTO DE SANTA MONICA 106"], 

		["4101", "G ARAGON,EDO MEX", "AVENIDA CENTRAL # 263"], 

		["4149", "COSMOVITRAL,EDO MEX", "SEBASTIAN LERDO DE TEJADA # 201"], 

		["4153", "ZONA ESMERALDA,EDO MEX", "JIMENEZ CANTU 113-A"], 

		["4154", "JARDINES DE BELLAVISTA, MEX", "FUENTES DE SATELITE # 146 NIVEL L-2"], 

		["4182", "SAN MATEO,EDO MEX", "ADOLFO LOPEZ MATEOS # 201 KMAR"], 

		["4198", "SAN CARLOS,EDO MEX", "JUAREZ 216 C.C. SN CARLOS LOC 40-44"], 

		["4199", "LERMA,EDO MEX", "AV. DE LAS PARTIDAS MZA. 8 LOTE IA"], 

		["4203", "SEC GILLETTE,EDO MEX", "ATOMO # 13 ENTRE PROTON Y ELECTRON"], 

		["4214", "SEC FORD CUAUTITLAN,EDO MEX", "KM 36.5 CARR MEX-QUERETARO S/N"], 

		["4215", "SEC INFRA,EDO MEX", "FELIX GUZMAN # 16 Y PERIFERICO"], 

		["4271", "CLUB DE GOLF HACIENDA,EDO MEX", "DE LOS JINETES # 155 LOC G Y H"], 

		["4274", "LAS FUENTES,EDO MEX", "LAS FUENTES # 34"], 

		["4275", "SEC NISSAN LERMA", "CIRCUITO DE LA INDUSTRIA SUR S/N"], 

		["4311", "GENERAL MOTORS,EDO MEX", "INDUSTRIA MINERA # 700"], 

		["4344", "ATIZAPAN NORTE,MEX", "AV SNMATEO 17PZACRYSTAL L11-14Y29 ZC"], 

		["4345", "PUENTE DE VIGAS,MEX", "AV PRESIDENTE JUAREZ 33 PZAVIGAS 1-3"], 

		["4346", "TOREO,MEX", "BLVD MANUEL A CAMACHO 479 CC LOC A-8"], 

		["4347", "OTUMBA,MEX", "PLAZA DE LA CONSTITUCION No. 5"], 

		["4349", "HUEHUETOCA,MEX", "CARR. JORABAS-HUEHUETOCA S/N"], 

		["4403", "AMECAMECA,EDO MEX", "AV. HIDALGO No. 21"], 

		["4405", "A. CUATITLAN,MEX", "AUTOPISTA MEXICO-QUERETARO KM 37 1/2"], 

		["4408", "B.A. TEXCOCO,EDO DE MEX", "PROL. 16 DE SEPTIEMBRE S/N ESQ 2 MAR"], 

		["4414", "GRAND PLAZA TOLUCA,MEX", "AV. BENITO JUAREZ No. 211 LOCAL 58"], 

		["4420", "SEC ANDERSON CLAYTON,MEX", "AV. TEPALCAPA No. 2"], 

		["4427", "TULTEPEC,MEX", "AV. 16 DE SEPTIEMBRE S/N"], 

		["4428", "APAXCO,MEX", "PLAZA MELCHOR OCAMPO 2 ENTRE 2 MARZO"], 

		["4429", "JARDINES DEL ALBA,MEX", "PARQUE DE BOSENCHEVE 18 LOTE 9"], 

		["4430", "SANTA CECILIA,MEX", "CALZ. SANTA CECILIA No. 17"], 

		["4439", "SEC S.E.I.E.M. TOLUCA,MEX", "AV. RIO PAPALOAPAN No. 1306"], 

		["4440", "JARDINES DE MORELOS,MEX", "AV. CENTRAL 615"], 

		["4441", "LAS TORRES PILARES,MEX", "EMILIO CARRANZA No. 2"], 

		["4461", "NEZA VILLADA,MEX", "VICENTE VILLADA 248-A LOTE 50 Y 33"], 

		["4463", "GUSTAVO BAZ,MEX", "GUSTAVO BAZ 220 LOTE 6-C"], 

		["4469", "SAN SEBASTIAN,MEX", "ISIDRO FABELA 400 ENTRE I.PEREZ/PI&Ntilde;A"], 

		["4499", "SEC. NESTLE,MEX", "CARR MEX-TOLUCA KM 62.5 INTER.NESTLE"], 

		["4535", "SEC TRIBUNAL TOLUCA,MEX", "TRIB.SUP.JUST.NICOLAS SANJUAN 104"]

	];



var sucGua = 

	[

		["104", "CELAYA,GTO", "AV ALVARO OBREGON Y GONGORA"], 

		["112", "IRAPUATO,GTO", "JUAREZ No 11"], 

		["113", "LEON,GTO", "5 DE MAYO 125 ESQ.BLVD.A.L.MATEOS "], 

		["164", "GUANAJUATO,GTO", "PLAZA DE LOS ANGELES Y AV. JUAREZ "], 

		["262", "SALAMANCA,GTO", "HIDALGO Y TOMASA ESTEVEZ No 204 "], 

		["264", "DOLORES HIDALGO,GTO", "PLAZA PRINCIPAL No. 15"], 

		["290", "CORTAZAR,GTO", "PORTAL CONSTITUCION 25-C"], 

		["302", "VALLE DE SANTIAGO,GTO", "ARTEAGA No 78"], 

		["303", "MOROLEON,GTO", "HIDALGO No 19"], 

		["304", "SALVATIERRA,GTO", "ZARAGOZA 2 ESQ HIDALGO"], 

		["309", "APASEO EL ALTO,GTO", "JARDIN CUAUHTEMOC No 139"], 

		["310", "SAN JOSE ITURBIDE,GTO", "ALLENDE No. 6"], 

		["312", "EL BARRIO,GTO", "AQUILES SERDAN NO. 801 ESQ.MOCTEZUMA "], 

		["313", "JARAL DEL PROGRESO,GTO", "HIDALGO 200"], 

		["314", "YURIRIA,GTO", "PORTAL HIDALGO 2"], 

		["327", "SAN FCO. DEL RINCON,GTO", "DIAZ MIRON ESQ FCO OROZCO MU&amp;OZ "], 

		["336", "CENTRO,LEON", "FCO.I.MADERO 125"], 

		["340", "ABASOLO,GTO", "PLAZA PRINCIPAL No 210"], 

		["413", "SILAO,GTO", "JARDIN PRINCIPAL NO. 8"], 

		["442", "LA SOLEDAD,GTO", "AV.MIGUEL ALEMAN 157"], 

		["475", "ESTADIO IRAPUATO,GTO", "GUERRERO 1434"], 

		["483", "SAN MIGUEL ALLENDE,GTO", "CANAL No 4"], 

		["486", "CUERAMARO,GTO", "VENUSTIANO CARRANZA 118"], 

		["570", "BLVD PONIENTE,GTO", "BLVD LOPEZ MATEOS No 1124 PTE"], 

		["603", "ANDRADE LEON,GTO", "BLVD.MARIANO ESCOBEDO ESQ.PRIVADA AT "], 

		["642", "JARDINES DE JEREZ,GTO", "BLVD.J.J.TORRES LANDA 4137"], 

		["692", "FAJA DE ORO,GTO", "ALTAMIRA # 702 ESQ. TAMPICO"], 

		["712", "VILLA INSURGENTES,GTO", "C.DE CHILPANCINGO Y ANTONIO MADRAZO "], 

		["752", "TECNOLOGICO CELAYA,GTO", "AV TECNOLOGICO 701"], 

		["754", "SAN LUIS DE LA PAZ,GTO", "MATAMOROS 11 ENTRE GUERRERO Y MORELO "], 

		["785", "CAMPESTRE-IRAPUATO,GTO", "BLVD. LAZARO CARDENAS # 1155"], 

		["794", "PURISIMA DE BUSTOS,GTO", "JARDIN PRINCIPAL 109"], 

		["841", "SAN FELIPE,GTO", "PORTAL PRADO No. 2"], 

		["926", "TRES GUERRAS,GTO", "PUERTA DE ORO 203 Y PASEO GTO"], 

		["928", "PLAZA GEMINIS,GTO", "BLVD. T.LANDA 4202 PZA.GEMIN.L.34-38 "], 

		["4015", "CM IRAPUATO,GTO", "BLVD. DEL BOSQUE # 1"], 

		["4034", "G SALAMANCA,GTO", "LAZARO CARDENAS # 600"], 

		["4053", "CM LEON INSURGENTES,GTO.", "PASEO DE LOS INSURGENTES"], 

		["4150", "JULIAN DE OBREGON,GTO", "INDUSTRIAL # 219 ESQ. DESPUNTADORES "], 

		["4151", "PROLONGACION JUAREZ,GTO.", "PROL. JUAREZ ESQ. PERLA"], 

		["4200", "SORIANA IRAPUATO,GTO", "ARBOLEDAS 1200 PC.JACARANDAS L-24-27 "], 

		["4216", "SEC MOULINEX,GTO", "AUT. QRO-IRAPUATO KM 36"], 

		["4258", "SEC FLEXI,GTO.", "BLVD FCO. VILLA # 201-1"], 

		["4295", "G SAN MIGUEL DE ALLENDE,GTO.", "SALIDA A QUERETARO KM I S/N"], 

		["4375", "PARAISOS,GTO", "PASEO DE LOS INSURGENTES 303"], 

		["4379", "ROMITA,GTO", "PORTAL OCAMPO 21"], 

		["4399", "URIANGATO,GTO", "PORTAL INDEPENDENCIA No.8"], 

		["4400", "APASEO EL GRANDE,GTO A", "JARDIN HIDALGO No. 107"], 

		["4415", "MANUEL DOBLADO,GTO", "HIDALGO No. 113"], 

		["4433", "COLONIAS,GTO", "ZARAGOZA S/N ESQ BLV JUVENTINO ROSAS "], 

		["4495", "PLAZA MAYOR,GTO", "J.M.CLOUTHIER INT.PZA.MAYOR LOCAL 5 "], 

		["4496", "CASIMIRO LICEAGA,GTO", "CASIMIRO LICEAGA 1449 ENT.J.AMOR RDZ "], 

		["4500", "SEC PEMEX SALAMANCA,GTO", "TIERRA BLANCA 400 ESQ.CALLEA P1 PEME "], 

		["4503", "BA IRAPUATO,GTO", "DIAZ ORDAZ 1333 LOCAL H ENT.AV REVOL "]

	];



var sucGue = 

	[

		["18", "ZIHUATANEJO,GRO.", "CUAUHTEMOC 4"], 

		["37", "LA SABANA, GRO.", "BLVD. LOPEZ PORTILLO ESQ. EJE CENTRA "], 

		["44", "OMETEPEC,GRO", "PLAZA ZARAGOZA No. 1"], 

		["62", "SAN MARCOS, GRO.", "ZARAGOZA 3"], 

		["95", "HORNOS ACAPULCO,GRO", "COSTERA MIGUEL ALEMAN ESQ VIZCAINO "], 

		["317", "PROGRESO ACAPULCO,GRO", "CUAUHTEMOC ESQ.DIEGO HURTADO 739 "], 

		["444", "ATOYAC DE ALVAREZ,GRO", "GRAL. JUAN ALVAREZ NTE.8"], 

		["456", "COSTERA,GRO", "AV COSTERA MIGUEL ALEMAN 2085"], 

		["490", "CHILAPA,GRO", "AV REVOLUCION 207"], 

		["565", "TELOLOAPAN,GRO", "PLAZA EUTIMIO PINZON 10"], 

		["814", "IXTAPA,GRO.", "C.COM. LOS ARCOS 16/16A MZA 2 SEC. 1 "], 

		["911", "TAXCO,GRO", "B. JUAREZ # 19 PZA DEL EXCONVENTO "], 

		["924", "COSTA AZUL,GRO", "AV. COSTERA M. ALEMAN ESQ.LAUREL "], 

		["925", "CONDESA, GRO.", "BLVD. COSTERA M. ALEMAN # 78 LOC. 1 "], 

		["4011", "CM ACAPULCO VISTA ALEGRE,GRO.", "RUIZ CORTINEZ # 13"], 

		["4054", "CM ACAPULCO LA DIANA,GRO.", "FARALLON DEL OBISPO # 216"], 

		["4096", "EJIDO,GRO", "CONSTITUYENTES ESQ. EJIDO"], 

		["4124", "BG ACAPULCO RENACIMIENTO,GRO", "CARR. MEX-ACAP. KM 4.5"], 

		["4220", "BG ACAPULCO CENTRO,GRO", "CUAUHTEMOC S/N ESQ J.R. CABRILLO "], 

		["4309", "PRICE ACAPULCO", "BLVD DE LAS NACIONES # 34-A"], 

		["4390", "IMSS ACAPULCO,GRO", "DIEGO HURTADO DE MENDOZA S/N"], 

		["4391", "IMSS ZIHUATANEJO,GRO", "OLINALA Y RETORNO No. 1"], 

		["4392", "IMSS CHILPANCINGO,GRO", "AV. MIGUEL ALEMAN No. 70"], 

		["4393", "IMSS IGUALA,GRO", "AV JOAQUIN BARANDA No. 6, 1ER PISO "], 

		["4449", "CAMINOS,GRO", "AV. DE LOS INSURGENTES No. 10"], 

		["4450", "COYUCA DE BENITEZ,GRO", "AV. PALMERAS No. 33"], 

		["4455", "ORFEBRES,GRO", "6a. CALLE DE GALEANA No. 64"], 

		["4516", "CM CHILPANCINGO,GRO", "PROLONGAC. BALTAZAR LEYVA MANCILLA 3 "]

	];



var sucHid = 

	[

		["12", "TULA,HGO", "LEANDRO VALLE ESQ. AV JUAREZ"], 

		["35", "CA HIDALGO,HGO.", "BLVD COOPERATIVISMO # 1"], 

		["55", "TEPEAPULCO,HGO", "INDEPENDENCIA 2"], 

		["66", "HUEJUTLA,HGO", "HIDALGO No. 1, ESQ. MORELOS"], 

		["122", "PACHUCA,HGO", "PLAZA INDEPENDENCIA 105 PACHUCA HGO "], 

		["162", "TULANCINGO,HGO", "HIDALGO ORIENTE 203"], 

		["455", "ACTOPAN,HGO", "PLAZA JUAREZ 4"], 

		["461", "HUICHAPAN,HGO", "PEDRO MA ANAYA Y FELIPE ANGELES "], 

		["463", "PROGRESO DE OBREGON,HGO", "PLAZA DE LA CONTISTUCION Y E ZAPATA "], 

		["487", "IXMIQUILPAN,HGO", "AV GRAL FELIPE ANGELES No 18"], 

		["693", "MADERO,HGO", "CARR A TULANGINGO ESQ METZTITLAN "], 

		["769", "ZIMAPAN,HGO", "PLAZA DE LA CONSTITUCION 15 /NR Y BJ "], 

		["853", "APAN,HGO", "HIDALGO No. 1 ESQ. REFORMA"], 

		["949", "CENTRO MINERO,HGO", "CTO. COM. PERISUR LOC. 31 A 33"], 

		["985", "TIZAYUCA,HGO", "HIDALGO S/N ENTRE JUAREZ"], 

		["4221", "BG TULANCINGO,HGO.", "CARR MEX-TUXPAN 1385"], 

		["4223", "BG PACHUCA,HGO", "PZA DE LAS AMERICAS S/N C.ABASTOS "], 

		["4464", "CD. SAHUGUN,HGO", "ALLENDE LOTE 1 ENT.OTE Y NICOLAS ROM "], 

		["4465", "BLVD. EMILIANO ZAPATA,HGO", "BLVD EMILIANO ZAPATA S/N /21 MARZO "], 

		["4502", "SEC. PEMEX TULA,HGO", "CARR JOROBAS-TULA KM 26 INT.REF.HGO "]

	];



var sucJal = 

	[

		["14", "TALA, JAL.", "NICOLAS BRAVO No 10"],

		["24", "TOTOTLAN, JAL.", "AV JUAREZ 2 ESQ HIDALGO"],

		["47", "ACUEDUCTO,JAL", "AV. ACUEDUCTO 6050 LOCAL 15"],

		["67", "EL SALTO,JAL", "HIDALGO # 46"],

		["77", "AMERICAS COUNTRY JAL", "AV AMERICAS 981"],

		["192", "OCOTLAN JAL", "HIDALGO No 230"],

		["195", "LA BARCA JAL", "HIDALGO Y ZARAGOZA"],

		["201", "ATOTONILCO,JAL.", "5 DE FEBRERO 19"],

		["214", "SANTA MONICA,JAL", "AV HGO 595 ESQ CONTRERAS MEDELLIN "],

		["215", "INDEPENDENCIA JAL", "PLZA TAPATIA BLOQUE E LOC 6 7 8 Y 9 "],

		["225", "AUTLAN JAL", "GUILLERMO PRIETO ESQ ALVARO OBREGON "],

		["253", "TLAQUEPAQUE JAL", "INDEPENDENCIA No 88"],

		["255", "NI&amp;OS HEROES,JAL", "AV. ENRIQUE DIAZ DE LEON 785"],

		["274", "PROVIDENCIA,JAL", "PABLO NERUDA 2953 ESQ. TERRANOVA "],

		["315", "ABASTOS,JAL", "LAZARO CARDENAS 2440 ESQ PLATANO "],

		["351", "PLAZA PATRIA,JAL", "CTO COMERCIAL PZA PATRIA LOC 6 Y 12 "],

		["361", "ZAPOTILTIC,JAL", "REFORMA 75 ENT. N.BRAVO Y C.TAMAZULA "],

		["373", "AMECA,JAL", "J GUADALUPE VAZQUEZ L No 18"],

		["380", "PLAZA DEL SOL,JAL", "AV LOPEZ MATEOS 1418 ESQ TIZOC"],

		["389", "GONZALEZ GALLO,JAL", "CALZ GONZALEZ GALLO 535 SEC REFORMA "],

		["399", "TAMAZULA JAL", "JAVIER MINA No 32 ORIENTE"],

		["401", "TUXPAN JAL", "PORTAL MORELOS 10"],

		["406", "JALOSTOTITLAN,JAL", "GONZALEZ HERMOSILLO No. 58"],

		["410", "TEOCALTICHE,JAL", "HIDALGO No. 134 ENTRE ZARAGOZA"],

		["416", "CASIMIRO CASTILLO,JAL", "REVOLUCION S/N ENTRE ALVARO OBREGON "],

		["423", "TEQUILA JAL", "JUAREZ No 37 ESQ JESUS RDZ DE H. "],

		["433", "CHAPALA JAL", "MADERO No 222"],

		["449", "EL GRULLO JAL", "OBREGON 4 BAJOS"],

		["450", "PIHUAMO JAL", "HIDALGO No 18"],

		["460", "TECALITLAN JAL", "PORTAL VICTORIA 13"],

		["477", "SAN JUAN DE LOS LAGOS JAL", "FCO JAVIER NU&amp;O 7"],

		["495", "ZACOALCO DE TORRES,JAL", "ARISTA No 107 ENTRE J ANTONIO TORRES "],

		["567", "JARDINES DEL BOSQUE,JAL", "NI&amp;OS HEROES 2891"],

		["624", "PUERTA DE HIERRO,JAL", "PATRIA # 1744"],

		["680", "JAVIER MINA JAL", "JAVIER MINA # 1510"],

		["706", "JAMAY,JAL", "MADERO No 97"],

		["707", "LAS JUNTAS,JAL", "CALZD GOBERNADOR LUIS G CURIEL 3323 "],

		["708", "ARANDAS,JAL.", "PORTAL ALDAMA # 7"],

		["715", "RIO NILO,JAL", "R. NILO 7540 LOC. 72/73/74 C.C.LOMAS "],

		["736", "MELAQUE,JAL", "C.GOMEZ FARIAS T.EJIDAL /ARE.COM.HVH "],

		["762", "LAS ROSAS,JAL", "AV.LOPEZ MATEOS SUR 1952"],

		["779", "EL PALOMAR,JAL.", "PROLONGACION LOPEZ MATEOS"],

		["787", "ATEQUIZA JAL", "24 DE NOVIEMBRE No 3"],

		["806", "SAN MIGUEL EL ALTO,JAL", "PORTAL MORELOS 24 ENT.MORELOS Y MACI "],

		["891", "COLOMOS,JAL", "AV PATRIA 734 ESQ DUQUEIROS"],

		["912", "CAMINO REAL,JAL", "AV. NI&amp;O OBRERO 454"],

		["921", "ARTESANOS TONALA,JAL.", "FCO. I MADERO # 84"],

		["922", "CONCENTRO,JAL.", "VALLARTA 6503 LOC. 19,20,26 ZONA &quot;E&quot; "],

		["936", "TEPEYAC,JAL", "GUADALUPE 4797 L 2-B ESQ M.CLOUTHIER "],

		["943", "TRANSITO,JAL", "PROL.ALCALDE 1946 ESQ.FELIX PALAV. "],

		["954", "CALZADA,JAL.", "INDEPENDENCIA NORTE # 1375,1377,1379 "],

		["961", "PLAZA MEXICO,JAL.", "MEXICO 3341 ESQ. HERODOTO"],

		["977", "MIRADOR, JAL.", "AV. PATRIA # 5005"],

		["980", "NORMALISTAS,JAL", "AV CIRCUNVALACION DIV.DEL NORTE 415 "],

		["984", "PLAZA GENOVESA,JAL", "FCO MEDINA ASCENCIO LOCAL 31 Y 31-A "],

		["987", "MEGAMERCADO,JAL", "AV.RAFAEL SANZIO 55 ESQ.CON VALLARTA "],

		["4002", "CM PLAZA LAS FUENTES,JAL.", "LOPEZ MATEOS SUR # 60-61"],

		["4036", "G OBLATOS,JAL.", "AV. CIRCUNVALACION # 2700"],

		["4037", "G TORRES,JAL.", "AV 8 DE JULIO # 1896"],

		["4038", "A. PLAZA MEXICO,JAL", "AV. MEXICO 3000"],

		["4040", "PLAZA MARINA,JAL", "FRANCISCO MEDINA ASENCIO S/N"],

		["4042", "G BELENES,JAL.", "AV. DEL MAIZ # 1300"],

		["4112", "L ARBOLEDAS,JAL", "ESPARZA # 518 Y RIO TEPATITLAN"],

		["4133", "G PLAZA LOS ALTOS,JAL", "ANACLETO GLZ. FLORES S/N"],

		["4136", "G ZAPOTLAN,JAL", "CONTINUACION CRUZ ROJA PA&Ntilde;O NTE. 20 "],

		["4137", "G CRUZ DEL SUR,JAL", "CRUZ DEL SUR # 3689"],

		["4138", "G PLAZA GUADALUPE,JAL", "NICOLAS COPERNICO # 2831"],

		["4191", "SEC LABORATORIOS PISA,JAL.", "ESPA&Ntilde;A 1840 /BRUZELAS Y VENEZUELA "],

		["4226", "G CALZADA,JAL.", "INDEPENDENCIA 500 Y PROSPERIDAD "],

		["4227", "G TLAQUEPAQUE,JAL.", "NI&Ntilde;OS HEROES 245 Y MADERO "],

		["4228", "G PLAZA UNIVERSIDAD,JAL", "PABLO NERUDA 4341 Y PATRIA"],

		["4229", "G EL SAUZ,JAL.", "COLON 4030 Y PATRIA E ISLA MEX. "],

		["4230", "G BOSQUE,JAL.", "NI&Ntilde;OS HEROES 2546 Y AV INGLATERRA "],

		["4231", "G CAMICHINES,JAL", "LAZARO CARDENAS 1531 Y CARR CUOTA "],

		["4253", "SEC MOLEX BANAMEX,JAL.", "PRODUCTIVIDAD ORIENTE # 305"],

		["4267", "ZAPOTLANEJO,JAL", "ALVARO OBREGON # 41"],

		["4291", "COPERNICO,JAL.", "MARIANO OTERO # 4419"],

		["4292", "STA. TERESITA,JAL.", "AMERICAS # 475"],

		["4308", "S.E.C. PHILIPS BANAMEX", "PERIFERICO SUR 7999"],

		["4319", "L MORE&Ntilde;A,JAL", "CARR LA BARCA BRISE&Ntilde;AS"],

		["4320", "L PLAZA CAPUCHINAS,JAL", "FELIZ RAMIREZ RENTERIA 1150"],

		["4321", "COUNTRY CLUB,JAL", "AMERICAS 1488 SAO PAULO Y MAR MEDIT "],

		["4434", "ZAPOPAN,JAL", "LAURELES 84 ENTRE LOPEZ COTILLA "],

		["4435", "SAN JUAN BOSCO,JAL", "ESTEBAN A. LATORRE 1699"],

		["4436", "PLAZA REVOLUCION,JAL", "AV. REVOLUCION 2242"],

		["4460", "ALVARO OBREGON,JAL", "JAVIER MINA 450 ESQ.LEONA VICARIO "],

		["4471", "A. PLAZA ARBOLEDAS,JAL", "AV. ARBOLEDAS No. 2500"],

		["4472", "SANTUARIO,JAL", "ALCALDE 444 ENT.MANUEL ACU&Ntilde;A Y J.ALV "],

		["4473", "FELIPE ANGELES,JAL", "FELIPE ANGELES 355 ESQ FCO DE AYZA "],

		["4475", "LABORATORIOS PISA II,JAL", "CALLE 7 No.1308 ENT.CALLE 6 Y CALLE8 "],

		["4494", "SEC SOLECTRON,JAL", "PROL L. MATEOS 2915"],

		["4507", "TELETON NUEVO PROGRESO", "PIRINEOS 1930"],

		["4514", "ARALMEX,JAL", "CARRETERA EL SALTO-LA CAPILLA KM 3.5 "],

		["4534", "JETRO GUADALAJARA,JAL", "8 DE JULIO NUM. 2759"]

	];



var sucMch = 

	[

		["168", "ZITACUARO MICH", "EMILIO GARCIA ESQ L DE TEJADA PTE"], 

		["204", "APATZINGAN,MICH.", "CONSTITUCION DE 1814 No. 33"], 

		["223", "ZACAPU,MICH", "MORELOS # 134"], 

		["325", "MERCADO INDEPENDENCIA MICH", "VICENTE SANTA MARIA # 639"], 

		["354", "CIUDAD HIDALGO,MICH", "PLAZA CENTENARIO ESQ.VILLALONGIN"], 

		["368", "PURUANDIRO, MICH.", "GUERRERO No 11"], 

		["426", "TANGANCICUARO MICH", "PORTAL HIDALGO # 94"], 

		["427", "JIQUILPAN MICH", "PORTAL BRAVO 75"], 

		["428", "LOS REYES MICH", "PORTAL HIDALGO No 31"], 

		["434", "YURECUARO,MICH", "PORTAL NEGRETE No 8"], 

		["435", "MADERO PONIENTE,MICH", "AV MADERO PTE ESQ J DE ALVARADO 1610"], 

		["436", "PUREPERO,MICH", "PORTAL MORELOS No 57"], 

		["446", "NUEVA ITALIA,MICH", "PASCUAL OROZCO # 29"], 

		["447", "LAZARO CARDENAS MICH", "AV LAZARO CARDENAS 1646"], 

		["459", "PATZCUARO, MICH.", "PORTAL JUAREZ No 32"], 

		["480", "HUETAMO,MICH", "MADERO SUR # 2-A"], 

		["484", "AGUILILLA,MICH", "AV. JUAREZ No 71 ESQ. JESUS MADRIGAL"], 

		["542", "NUEVA VALLADOLID,MICH", "LAZARO CARDENAS # 1677"], 

		["632", "CAMELINAS,MICH", "AV. CAMELINAS # 1454 ESQ TCHAIKOVSKY"], 

		["641", "ZINAPECUARO,MICH", "HIDALGO 40 ENTRE MORELOS"], 

		["673", "SANTIAGUITO MICH", "M BUENDIA 88 ESQ HEROES DE NACOZARI"], 

		["674", "SANTA MARIA DE GUIDO MICH", "AV CAMELINAS NO 916 ESQ HENDEL"], 

		["763", "TLAZAZALCA,MICH", "MORELOS ESQ HIDALGO 135"], 

		["823", "PLAZA CARRILLO,MICH", "&quot;MANUEL MU;IZ 493&quot;"], 

		["945", "CATEDRAL,MICH", "5 DE MAYO # 75 SUR"], 

		["953", "PLAZA PUREPECHA,MICH", "PASEO GRA. LAZARO CARDENAS ESQ. ROMA"], 

		["4140", "G PZA.ANA ZAMORA,MICH", "ZAMORA JACONA 1900"], 

		["4263", "LA HUERTA,MICH.", "VIRGO # 208"], 

		["4442", "SANTA MARIA,MICH", "J.J. TABLADA No. 589"], 

		["4443", "EL CAYACAL,MICH", "LAZARO CARDENAS 447"], 

		["4474", "VASCO DE QUIROGA,MICH", "BUCARELI 910 ENT.LACAS URUAPAN Y CAP"], 

		["4482", "CONSTITUCION,MICH", "JOSE MARIA MORELOS Y PAVON 73"], 

		["4532", "ADUANA LAZARO CARDENAS,MICH", "MELCHOR OCAMPO 32 EDIF. CURACRETO"], 

		["4803", "CPAE MORELIA,MICH", "CAMELINAS 3257 P.B."]

	];



var sucMor = 

	[

		["150", "CUAUTLA,MOR", "GALEANA 33"], 

		["248", "JOJUTLA,MOR", "M ALTAMIRANO ESQ RAFAEL ZAYAS E "], 

		["339", "PLAN DE AYALA,MOR", "PLAN DE AYALA # 801 ESQ. CENTRAL/NTE "], 

		["443", "YAUTEPEC,MOR", "CALLE VIRGINIA FABREGAS 11"], 

		["481", "CASINO DE LA SELVA,MOR", "CALZ LEANDRO VALLE Y MELCHOR OCAMPO "], 

		["500", "CIVAC CUERNAVACA,MOR", "AV CENTENARIO 21-3 FRACC CD INDUSTRI "], 

		["669", "MANANTIALES,MOR.", "INSURGENTES # 678 Y AGUA AZUL P.B. "], 

		["694", "VISTA HERMOSA,MOR", "VISTA HERMOSA # 326"], 

		["710", "TULIPANES,MOR", "AUT. MEX-ACAP. KM. 87.5"], 

		["773", "TEMIXCO,MOR", "C.FED.MEX/ACAP.S/N Y PZA.COM.TEMIXCO "], 

		["997", "CASA BLANCA,MOR", "AV. GRO. 110 PZA. CUERNAV. CTO. COM. "], 

		["4010", "CM CUERNAVACA CTO,MOR.", "AV. MORELOS"], 

		["4097", "BUENAVISTA,MOR", "BLVD. EMILIANO ZAPATA # 823-1"], 

		["4113", "CARR CUERNAVACA,MOR", "BLVD.CUAUHNAHUAC KM 1.5 ESQ.JACARAND "], 

		["4128", "CM PLAZA JACARANDAS,MOR", "PASEO DE CUAUHNAHUAC # 101"], 

		["4380", "&quot;NI;O ARTILLERO,MOR&quot;", "JOSE PERDIZ No. 21"], 

		["4394", "IMSS ZACATEPEC,MOR", "AV. LAZARO CARDENAS S/N"], 

		["4395", "IMSS CUERNAVACA,MOR", "BAJADA CHAPULTEPEC No.6"], 

		["4396", "IMSS CUAUTLA,MOR", "CAMACHO MOLINA No.111"], 

		["4417", "OAXTEPEC,MOR", "ESTACION VIEJA S/N LOCALES 4,5,6 "], 

		["4448", "ANTIGUA ESTACION,MOR", "15 DE MARZO No. 407"], 

		["4456", "JIUTEPEC,MOR", "20 DE NOVIEMBRE No. 25"], 

		["4466", "BAXTER,MOR", "AV. DE LOS 50 METROS No. 2"]

	];



var sucNay = 

	[

		["407", "IXTLAN DEL RIO NAY", "PORTUGAL JUAREZ NO. 50"], 

		["408", "AHUACATLAN,NAY.", "HIDALGO 46 P.B."], 

		["409", "COMPOSTELA,NAY.", "HIDALGO NO. 8 SUR"], 

		["653", "LA CRUZ,NAY", "ESTEBAN BACA CALDERON # 5"], 

		["4078", "L PLAZA DE ALICA,NAY", "AV. UNIVERSIDAD Y AV. INSURGENTES"]

	];



var sucNL =

	[

		["56", "VILLA DE SANTIAGO, N.L.", "ABASOLO No.111"], 

		["117", "MONTERREY 400", "PADRE MIER #102 OTE. ESQ. JUAREZ CON "], 

		["186", "PINO SUAREZ,NL", "PINO SUAREZ ESQ. ARTEAGA"], 

		["265", "NOGALAR", "NOGALAR 500"], 

		["300", "ZARAGOZA", "ZARAGOZA SUR 1000 ESQ. HIDALGO"], 

		["348", "MADERO ORIENTE,NL", "PROL.MADERO Y CONSTITUYENTES DE N.L. "], 

		["392", "INDUSTRIAL GRO,NL", "GUERRERO NORTE 2929"], 

		["417", "CADEREYTA N L", "AV HIDALGO No 116 OTE"], 

		["439", "ALLENDE N L", "JUAREZ No 103"], 

		["554", "MONTEMORELOS N L", "COLON ESQ ZARAGOZA"], 

		["557", "SAN NICOLAS", "AV UNIVERSIDAD 517 PTE."], 

		["558", "CONTRY", "AV. EUGENIO GARZA SADA 3367 SUR "], 

		["621", "OBISPADO", "CONSTITUCION # 1965 PTE."], 

		["678", "RUIZ CORTINEZ,NL", "RUIZ CORTINES 2000 PTE. ESQ.EDISON "], 

		["679", "CUMBRES,NL", "PASEO DE LOS LEONES 2408"], 

		["795", "GONZALITOS", "AV. INSURGENTES 2500"], 

		["796", "LINARES N L", "AV HIDALGO No 329"], 

		["929", "ARCO INDEPENDENCIA", "PINO SUAREZ 928 NTE"], 

		["930", "TECNOLOGICO,NL", "AV. GARZA SADA # 2850 SUR"], 

		["931", "HEROES", "CALZ. MADERO 1552 OTE."], 

		["969", "BRISAS,NL", "AV. LAZARO CARDENES 4000"], 

		["973", "GARZA SADA", "AV. EUGENIO GARZA SADA S/N"], 

		["979", "PLAZA RIO", "SAN PEDRO # 801 LOC. 14-16"], 

		["988", "INDUSTRIAL CONDUCTORES", "AV. LOPEZ MATEOS 700"], 

		["4069", "S SAN PEDRO,NL", "HUMBERTO LOBO Y RIO GUADARQ. # 520 "], 

		["4070", "S SAN NICOLAS,NL", "UNIV. Y FRAY BARTOLOME DE LAS CASAS "], 

		["4071", "S LINDAVISTA,NL", "BONIFACIO # 600"], 

		["4072", "S CUMBRES,NL", "ALEJANDRO DE RODAS # 3102-A"], 

		["4073", "S LOS FRESNOS,NL", "MANUEL HERRERA # 101"], 

		["4074", "S FELIX U. GOMEZ,NL", "FELIX U. GOMEZ Y LOS ANGELES # 4100 "], 

		["4092", "MANUEL BARRAGAN,NL", "M. BARRAGAN # 551 ESQ CALLE 5A"], 

		["4105", "S SANTA CATARINA,NL", "HIDALGO 202 ESQ. BLVD DIAZ ORDAZ "], 

		["4165", "PASEO DE LOS LEONES,NL", "P. DE LOS LEONES 1901 Y SAN ANGEL "], 

		["4168", "BOSQUES DEL VALLE,NL", "B. DE CHAPULTEPEC 103 Y VASCONCELOS "], 

		["4194", "SAN AGUSTIN,NL", "BATALLON DE SAN PATRICIO # 1000 "], 

		["4201", "SANTO DOMINGO,NL", "AV. SANTO DOMINGO # 1000 LOTE 2 "], 

		["4213", "S SANTO DOMINGO,NL", "D.D. DE BERLANGA Y STO DOMINGO L-6 "], 

		["4234", "G GUADALUPE,NL", "LAZARO CARDENAS Y JUAREZ S/N"], 

		["4235", "G LOS ANGELES,NL", "FELIX GALVAN # 400 Y ROBERTO SADA "], 

		["4236", "G CIGARRERA,NL", "MADERO # 2450 PONIENTE"], 

		["4237", "G ANAHUAC,NL", "M.BARRAGAN # 325 NTE Y FRAY B.CASAS "], 

		["4238", "G TECNOLOGICO,NL", "EUGENIO GARZA SADA # 699"], 

		["4239", "G LINDAVISTA,NL", "PROLONGACION MADERO 4422 OTE."], 

		["4269", "COLINAS,NL", "PUERTA DEL SOL Y MANUEL M. PONCE "], 

		["4270", "LA FAMA,NL", "DIAZ ORDAZ # 153-A"], 

		["4307", "SANTA MARIA,NL", "PABLO LIVAS # 7500 OTE."], 

		["4324", "G MITRAS,NL", "AV. RUIZ CORTINES NO. 2401 PTE. "], 

		["4328", "FIDEL VELAZQUEZ,NL", "AV. FIDEL VELAZQUEZ S/N DEFINIDO "], 

		["4329", "NUEVA LINDAVISTA,NL", "AV. RUIZ CORTINES NO.1300 OTE."], 

		["4330", "LINCOLN,NL", "AV. LINCOLN NO. 4010"], 

		["4388", "S LA PUERTA,NL", "URANO 2620"], 

		["4467", "FELIX U. GOMEZ,NL", "RUIZ CORTINEZ 3309 ENT PABLO A GARZA "], 

		["4468", "DIEGO DIAZ DE BERLANGA,NL", "DIEGO DIAZ DE BERLANGA 805"], 

		["4477", "APODACA,NL", "PORFIRIO DIAZ 607 ENT.BLVD.C.SALINAS "], 

		["4480", "VISTA HERMOSA,NL", "ENRIQUE C LIVAS 200 ENT.ARG.Y PARAG. "], 

		["4485", "SEC PEMEX CADEREYTA,NL", "CARR. A REYNOSA KM. 36"], 

		["4491", "CARR. VALLE ORIENTE,NL", "AV. LAZARO CARDENAS 900 OTE."], 

		["4508", "PASEO DE LAS AMERICAS,NL", "PASEO DE LAS AMERICAS 110"], 

		["4511", "EXPO GUADALUPE,NL", "AV. CENTRAL 103 ENTRE BENITO JUAREZ "], 

		["4523", "ADUANA PUENTE COLOMBIA,NL", "CARR.NVO.LAREDO PIED. NGRAS. KM 34.5 "], 

		["4809", "EL CERCADO,NL", "CARRETERA NACIONAL 104"]

	];



var sucOax = 

	[

		["28", "TEHUANTEPEC,OAX", "AV. JUAREZ No. 9"], 

		["120", "OAXACA OAX", "HIDALGO No 821 ESQ ARMENTA Y LOPEZ "], 

		["182", "SALINA CRUZ OAX", "GUAYMAS 22"], 

		["193", "CD IXTEPEC OAX", "AV. 16 DE SEPTIEMBRE ESQ.MOCTEZUMA "], 

		["388", "TUXTEPEC OAX", "AV INDEPENDENCIA 256 ESQ CALLE RAYON "], 

		["398", "JUCHITAN OAX", "5 DE SEPTIEMBRE 12"], 

		["578", "POCHUTLA,OAX", "CONSTITUCION 3"], 

		["599", "HUATULCO OAX", "JUAREZ ESQ. POCHULA STA CRUZ SECC. A "], 

		["639", "PUTLA,OAX.", "CALLE 3 OAXACA # 21"], 

		["682", "MARQUESADO, OAX.", "MORELOS # 202 P.B. ESQ.PORF.DIAZ "], 

		["733", "TLACOLULA OAX", "AV 2 DE ABRIL PORTAL FLORIDA ESQ M O "], 

		["734", "TLAXIACO, OAX", "COLON 1"], 

		["753", "OCOTLAN DE MORELOS,OAX", "PORTAL XICOTENCATL No. 1"], 

		["771", "ZIMATLAN OAX", "PROGRESO # 2 Y JUAREZ"], 

		["776", "JUXTLAHUACA,OAX.", "ZARAGOZA SUR 202"], 

		["782", "TAPANATEPEC,OAX.", "MARTIN MELENDEZ # 48"], 

		["805", "LAGUNAS OAX", "COOPERATIVISMO ESQ BLVD CRUZ AZUL "], 

		["913", "PLAZA DEL VALLE,OAX.", "UNIVERSIDAD # 139 PLAZA DEL VALLE "], 

		["914", "PUERTO ESCONDIDO,OAX.", "PEREZ GAZGA # 314"], 

		["915", "PINOTEPA,OAX.", "PORFIRIO DIAZ # 112"], 

		["993", "HUAJUAPAN DE LEON,OAX.", "PORFIRIO DIAZ ESQ. AQUILES SERDAN "], 

		["4031", "SEC PEMEX SALINA CRUZ,OAX", "CALZ ACCESO A REFIN.ING.A.DOVALI S/N "], 

		["4032", "G REFORMA,OAX.", "HEROICO COLEGIO MILITAR # 1010"], 

		["4164", "C. DE ABASTOS,OAX.", "PERIFERICO # 715 LETRA B"], 

		["4336", "ANDADOR TURISTICO,OAX", "AURELIO VALDIVIELSO NO. 116"], 

		["4411", "CANTERAS,OAX", "CARR. INTERNACIONAL No. 5"], 

		["4509", "SEC T.M. SALINA CRUZ,OAX", "PROL. CALZADA TENIENTE AZUETA S/N "], 

		["4804", "CPAE OAXACA,OAX", "CALD. PORFIRIO DIAZ 321"]

	];



var sucPue = 

	[

		["27", "CUETZALAN, PUE.", "ALVARADO No 110"], 

		["31", "SAN MARTIN,PUE.", "BENITO JUAREZ # 101 ESQ. ZARAGOZA "], 

		["41", "TECAMACHALCO,PUE", "3 ORIENTE NO. 409"], 

		["45", "ZACATLAN,PUE", "AV. 5 DE MAYO No.11"], 

		["49", "PLAZA LORETO", "CALZADA IGNACIO ZARAGOZA 200"], 

		["159", "TEZIUTLAN PUE", "HIDALGO Y RIVA PALACIO"], 

		["180", "XICOTEPEC DE JUAREZ PUE", "IGNACIO ZARAGOZA # 126"], 

		["184", "HUAUCHINANGO PUE", "PORTAL ZARAGOZA No 3-A"], 

		["277", "CHOLULA PUE", "MORELOS No 8"], 

		["387", "DEFENSORES PUE", "DIAGONAL DEFENSORES 470 ESQ 11 NTE "], 

		["526", "ATLIXCAYOTL,PUE", "AV. INDEPENDENCIA 14"], 

		["609", "BOULEVARD VALSEQUILLO PUE", "BLVD. HEROES 5 DE MAYO # 502"], 

		["610", "LAS ANIMAS", "39 PONIENTE CIRC. INT. # 3302 P.B. "], 

		["644", "SAN LORENZO PUE", "ADOLFO LOPEZ MATEOS # 1800"], 

		["735", "ACATZINGO PUE", "JARDIN DE LOS INSURGENTES # 103 P.B. "], 

		["780", "IZUCAR DE MATAMOROS,PUE", "CENTENARIO NO. 5"], 

		["781", "ATLIXCO,PUE", "INDEPENDENCIA # 1903"], 

		["813", "ZONA INDUSTRIAL PUEBLA 2000", "KM 112 CARR LIBRE PUEBLA-TEHUACAN "], 

		["826", "PLAZA SAN PEDRO", "BLV.NTE Y 15 DE MAYO LOC.20-21,50-51 "], 

		["849", "GALERIA ANIMAS", "BOLVD.ATLIXCO 3154"], 

		["4012", "CM PUEBLA CENTRO,PUE.", "7 SUR # 1910"], 

		["4055", "CM PUEBLA SAN PEDRO,PUE.", "BLVD. NTE. HEROES 5 DE MAYO # 2410 "], 

		["4093", "CENTRAL DE ABASTOS PUEBLA,PUE.", "CTO. INTERIOR SUR # 12-A"], 

		["4094", "LA NORIA,PUE", "CTO. INT. # 1939 ESQ. CALLE 21 SUR "], 

		["4095", "CENTRAL DE AUTOBUSES PUEBLA,PUE", "PZA C.CAMIONERA Y BLVD.NTE/C.SERDAN "], 

		["4098", "MERCADO 16 DE MARZO,PUE", "CALLE 3 AGUSTIN A CACHO # 332"], 

		["4125", "BG PUEBLA FUERTES,PUE", "BLVD. HEROES 5 DE MAYO"], 

		["4126", "BG PUEBLA LIBRAMIENTO,PUE", "ESQ.PROL.16 OTE.5605 CARR.LIBRE A T. "], 

		["4127", "B.A. MAYORAZGO,PUE", "PROL. 11 SUR 8307"], 

		["4143", "MEC VOLKSWAGEN,PUE", "KM 116 AUTOP. MEX-PUEBLA"], 

		["4160", "LAS MARGARITAS,PUE.", "SAN BALTAZAR 3230 LOC-B8/B9 C.COM. "], 

		["4161", "PLAZA VICTORIA,PUE.", "5 DE MAYO # 408"], 

		["4162", "FINANZAS,PUE.", "CALLE 11 OTE. 2401 ESQ. AV. 24 SUR "], 

		["4163", "VOLCANES,PUE.", "CALLE 31 PONIENTE # 908"], 

		["4195", "CD UNIVERSITARIA,PUE", "BLVD. VALSEQUILLO # 6323 LOCAL D "], 

		["4260", "BLVD I. ZARAGOZA,PUE", "IGNACIO ZARAGOZA # 245"], 

		["4262", "REVOLUCION,PUE.", "25 PONIENTE # 2108"], 

		["4302", "RECTA A CHOLULA,PUE.", "RECTA A CHOLULA # 4701 ESQ. JALPAN "], 

		["4303", "SAN MANUEL,PUE.", "CALLE 14 SUR 4325 /DIAZ ORDAZ Y MAD. "], 

		["4335", "EL CARMEN,PUE", "AV. PONIENTE NO.123"], 

		["4381", "CHIPILO,PUE", "I6 DE SEPTIEMBRE No. 3"], 

		["4447", "REFORMA TEHUACAN,PUE", "AV. REFORMA No. 202"]

	];



var sucQue = 

	[

		["38", "PLAZA DEL PARQUE,QRO", "PROL.CORREGIDORA Y LIBRAM. LOC. II-B"], 

		["40", "TEQUISQUIAPAN,QRO", "NI&amp;OS HEROES 40"], 

		["91", "QUERETARO ZARAGOZA,QRO", "AV IGNACIO ZARAGOZA PONIENTE 150"], 

		["147", "QUERETARO QRO", "16 DE SEPTIEMBRE 1 PONIENTE"], 

		["289", "SAN JUAN DEL RIO,QRO", "AV JUAREZ No 19 PTE"], 

		["547", "CONSTITUYENTES,QRO", "AV CONSTITUYENTES ESQ DIAG 20 NOV"], 

		["731", "AMEALCO,QRO", "PLAZA DE LA CONSTITUCION 11"], 

		["917", "TEC-100,QRO", "TECNOLOGICO # 100"], 

		["4003", "CM SAN JUAN DEL RIO,QRO.", "JUAREZ PONIENTE # 140"], 

		["4079", "CARR QUERETARO,QRO", "BERNARDO QUINTANA"], 

		["4219", "CM Q. ZARAGOZA,QRO.", "I. ZARAGOZA 150 ESQ PONIENTE"], 

		["4264", "CARRILLO PUERTO,QRO.", "SOL # 1 C.C.PZA.SOL LOC-23 AL 27"], 

		["4372", "ALAMOS,QRO", "CALLE DE CHOPO No. 2"], 

		["4377", "IMSS SAN JUAN DEL RIO,QRO", "IGNACIO PEREZ 2, PISO 2"], 

		["4378", "IMSS QUERETARO", "AV. 5 DE FEBRERO S/N ESQ. CALZ ZARAG"], 

		["4444", "FRANCISCO VILLA,QRO", "FRANCISCO VILLA 48 LIBRAM TEQUISQUIA"], 

		["4489", "SEC HOUSEHOLD PRODUCTS", "ACCESO III No. 216"], 

		["4490", "SEC KELLOGG'S,QRO", "CARR. AL CAMPO MILITAR KM. 1"], 

		["4533", "ADUANA QUERETARO,QRO", "AV. DEL FERROCARRIL S/N KM 348+340MT"]

	];



var sucQuin = 

	[

		["151", "CHETUMAL Q R", "JUAREZ No. 51 ESQ. ALVARO OBREGON"], 

		["612", "CARIBE, Q.R.", "AV CHICHEN ITZA 319 ESQ TANKAH"], 

		["657", "TERRAMAR, Q.ROO", "PLAZA TERRAMAR LOC. 37 Y 45"], 

		["742", "PLAYA DEL CARMEN,Q ROO", "BENITO JUAREZ 180-A POR 20 Y 25 NTE"], 

		["845", "TULUM, Q.ROO.", "AV. TULUM SUPER MANZ. 20 LOC. 1 Y 2"], 

		["890", "COZUMEL, Q.ROO", "5a. AV. SUR 8 x 1a. Y ADOLFO ROSADO"], 

		["4114", "CM CANCUN,Q ROO", "CABAH MANZANA 4 LOTE 2 SUPMZA 21"], 

		["4438", "UXMAL,Q ROO", "AV. LOPEZ PORTILLO LOT.17 MZNA 2 S/N"], 

		["4458", "ROYAL MAYAN,Q ROO", "KUKULCAN KM 16.5 FRAC L64 SECC A M53"], 

		["4525", "GOLONDRINA,Q.ROO", "P. JOAQUIN COLDWELL 2 LOCALES 5 AL 8"]

	];



var sucSin = 

	[

		["10", "GUASAVE, SIN.", "ZARAGOZA Y CORREGIDORA"], 

		["17", "ESTACION BAMOA, SIN.", "BLVD 16 SEPTIEMBRE ESQ I RAMIREZ "], 

		["114", "MAZATLAN SIN", "B JUAREZ ESQ ANGEL FLORES"], 

		["158", "LOS MOCHIS SIN", "GUILLERMO PRIETO ESQ HIDALGO"], 

		["170", "CULIACAN SIN", "ROSALES ESQ JUAN CARRASCO 103 PTE "], 

		["394", "JUAN CARRASCO SIN", "AV EJERCITO MEXICANO Y PAPAGAYO "], 

		["441", "GPE. CULIACAN,SIN.", "BLVD EMILIANO ZAPATA No 319 PTE "], 

		["583", "NAVOLATO,SIN", "ALMADA 333"], 

		["747", "CHOIX SIN", "ALVARO OBREGON 1"], 

		["751", "CONCORDIA SIN", "JAVIER MINA 2"], 

		["880", "G. LEYVA MAZ. SIN.", "GABRIEL LEYVA 2821 INT. 8-A"], 

		["894", "LA CAMPI&amp;A SIN", "DR MORA 1725 LOC.6 Y 61 C.C.CAMPI&amp;A "], 

		["895", "ANTONIO ROSALES SIN", "BLVD ANTONIO ROSALES E INDEPENDENCIA "], 

		["923", "DEL VALLE, CUL.,SIN.", "BLVD.ZAPATA ESQ. CARRETERA EL DORADO "], 

		["4013", "CM MAZATLAN,SIN.", "C. APOLO S/N"], 

		["4024", "L PLAZA DEL MAR,SIN.", "CARR.INT.ENTRE INSUR.Y RAFAEL BUELNA "], 

		["4025", "L HUMAYA,SIN.", "CARR.INT. 2015 NTE.Y REP. BRASIL "], 

		["4026", "L TRES RIOS,SIN.", "PROLONGACION TEOFILO NORIA # 1421 "], 

		["4027", "L JIQUILPAN,SIN.", "LIBERTAD 902 PTE. Y BLVD. ROSALES "], 

		["4028", "L PLAZA DEL RIO,SIN.", "RAFAEL BUELNA Y GUERRERO # 3 D"], 

		["4041", "L PLAZA FIESTA,SIN.", "AV L. CARDENAS E INSURGENTES S/N "], 

		["4075", "L GUASAVE,SIN.", "ARTURO PEIMBERT Y R. BUELNA # 105 "], 

		["4076", "L PLAZA FIESTA LAS PALMAS,SIN", "A. OBREGON Y BLVD. A. ROSALES S/N "], 

		["4106", "L PALMITO,SIN", "BLVD. EMILIANO ZAPATA # 1950"], 

		["4107", "L ABASTOS,SIN", "H. COLEGIO MILITAR # 3655"], 

		["4130", "Z PLAZA DEL VALLE,SIN.", "N. BRAVO Y MADERO S/N"], 

		["4131", "Z SAN MIGUEL,SIN", "PROL OBREGON Y CERRO DE BROTOS S/N "], 

		["4169", "CHAPULTEPEC,SIN.", "J.ORTIZ DE DOMINGUEZ PTE 352"], 

		["4170", "CARRANZA,SIN.", "V.CARRANZA 394 Y BENITO JUAREZ"], 

		["4171", "HUMAYA,SIN.", "BRASIL 1240 Y CARR. MEX/NOG NTE. "], 

		["4172", "LAS FUENTES,SIN.", "BLVD. A.L.MATEOS NTE. 1382"], 

		["4211", "SEC GOBIERNO DEL ESTADO DE SINALOA", "INSURGENTES S/N P.B. EDIF.SRIA.GOB. "], 

		["4240", "L EVORA,SIN.", "CARR INTERNACIONAL Y BLVD A.ROSALES "], 

		["4241", "L EL CONCHI,SIN.", "CARR INTERNACIONAL SUR # 52"], 

		["4317", "L DEL VALLE,SIN", "BLVD EMILIANO ZAPATA ESQ L. M.ROJAS "], 

		["4318", "L MAZATLAN.SIN", "CARR INTERNAL ESQ RIO PANUCO"], 

		["4323", "JARDINES DEL COUNTRY,SIN", "&quot;INDEPENDENCIA Y RIO DE CA;AS&quot; "], 

		["4351", "IMSS LOS MOCHIS,SIN", "ZARAGOZA Y NETZAHUALCOYOTL SN PCARAC "], 

		["4352", "IMSS GUASAVE,SIN", "ZARAGOZA Y BLAS VALENZUELA ALTOS S/N "], 

		["4368", "IMSS CULIACAN,SIN", "JUAN JOSE RIOS 50 PONIENTE"], 

		["4369", "IMSS MAZATLAN,SIN", "AV. DEL MAR No. 500"], 

		["4386", "SALVADOR ALVARADO,SIN", "BLVD ANTONIO ROSALES S/N ESQ SAL.ALV "], 

		["4387", "COLEGIO MILITAR,SIN", "CALZ. H COLEGIO MILITAR 3030"], 

		["4404", "AQUILES SERDAN,SIN", "BLVD FRANCISCO I MADERO S/N ESQ A.S. "]

	];



var sucSlp = 

	[

		["64", "MATEHUALA,SLP", "CONSTITUCION 105 ENTRE JUAREZ E HIDA"], 

		["127", "SAN LUIS POTOSI,SLP", "ALVARO OBREGON # 355 ESQ. ALLENDE"], 

		["178", "RIO VERDE,SLP", "HIDALGO 2"], 

		["198", "CIUDAD VALLES S L P", "HIDALGO 301 Y FCO. I. MADERO"], 

		["206", "CAPITAN CALDERA,SLP", "VENUSTIANO CARRANZA # 1655"], 

		["376", "TAMUIN S L P", "PEDRO A. DE LOS SANTOS ESQ. BRAULIO"], 

		["691", "PLAZA TANGAMANGA,SLP", "PROLONGACION S.DEGOLLADOS S/N EST.P."], 

		["775", "RICARDO B. ANAYA,SLP", "CARR. SAN LUIS - QRO. KM 3"], 

		["811", "EL DORADO,SLP", "NOREO RODRIGUEZ ESQ. CAP. CALDERA"], 

		["927", "CERRITOS,SLP", "PLAZA HIDALGO No. 7"], 

		["4020", "CM SAN LUIS POTOSI I,SLP", "HIMNO NACIONAL # 4005"], 

		["4056", "CM SAN LUIS POTOSI II,SLP", "SALVADOR NAVA S/N"], 

		["4057", "CM SAN LUIS POTOSI III,SLP", "ALBINO GARCIA # 1070"], 

		["4217", "G GLORIETA,SLP", "CARR CENTRAL FRENTE GLORIETA JUAREZ"], 

		["4298", "SEC LATINCASA,SLP", "INDUSTRIAS ESQ EJE 120"], 

		["4376", "LOMAS-SAN CARLOS,SLP", "CORDILLERA ARAKAN 503"], 

		["4389", "BOULEVARD VALLES,SLP", "BLVD MEXICO-LAREDO No.46"], 

		["4536", "SEC UNIVERSIDAD SLP", "MANUEL NAVA S/N"]

	];



var sucSon =

	[

		["1", "NOGALES,SON", "PLUTARCO ELIAS CALLES Y A.OBREGON SN"], 

		["6", "PACIFICO CD. OBREGON, SON.", "GUERRERO Y CALIFORNIA"], 

		["8", "MAGDALENA, SON.", "OBREGON 301 Y ALLENDE"], 

		["9", "AGUA PRIETA, SON.", "CUARTA S/N"], 

		["71", "SAN CARLOS SON", "LOCAL 1 PLAZA COMERCIAL SAN CARLOS"], 

		["76", "COLOSIO,SON", "BLVD COLOSIO GALERIAS 188 PERI.PTE."], 

		["111", "HERMOSILLO SON", "SERDAN No 39 PTE"], 

		["126", "CD. OBREGON,SON.", "5 DE FEBRERO No 200"], 

		["135", "GUAYMAS, SON.", "AV. SERDAN Y CALLE 20"], 

		["138", "NAVOJOA SON", "MORELOS 31"], 

		["167", "HUATABAMPO SON", "JUAREZ Y AV GUERRERO"], 

		["210", "CABORCA SON", "CALLE 3a OESTE 1"], 

		["211", "SAN LUIS RIO COLORADO SON", "MADERO ESQ CALLE 2a"], 

		["254", "PITIC HERMOSILLO SON", "MATAMOROS ESQ NAYARIT"], 

		["293", "EMPALME SON", "REFORMA ESQ NI&amp;OS HEROES"], 

		["396", "NOGALES CENTRO SON", "P. ELIAS CALLES Y AV A. OBREGON"], 

		["402", "CANANEA SON", "AV JUAREZ Y CALLE 6a ESTE S/N"], 

		["472", "PUERTO PE&amp;ASCO SON", "BLVD BENITO JUAREZ ESQ CAMPECHE"], 

		["601", "LA COLORADA SON", "DE LA PLATA ESQ DEL YESO LOC E Y F"], 

		["602", "NAVARRETE HERMOSILLO, SON.", "BLVD. NAVARRETE # 322-B"], 

		["791", "SEC MOLYMEX,SON.", "AV. OBREGON ESQ. CALLE 7"], 

		["810", "V. DEL YAQUI CD. OBREGON", "DR NORMAN E BOURLANG No 4803 SUR"], 

		["886", "VALLE DEL MAYO SON", "TALAMANTE 817 SUR"], 

		["887", "PROVIDENCIA-CAJEME SON", "MAYO ESQ CHIHUAHUA"], 

		["4021", "L OBREGON,SON.", "JALISCO Y AV INTERNACIONAL SUR"], 

		["4035", "L VADO DEL RIO,SON.", "PERIFERICO PTE. Y PASEO CANAL S/N"], 

		["4039", "L CAJEME,SON.", "M. ALEMAN S/N ZAR Y NO REELECCION"], 

		["4047", "TERMINAL MARITIMA GUAYMAS,SON", "MUELLE PEMEX S/N EDIF.ADMINISTRATIVO"], 

		["4077", "L PLAZA DEL MAYO,SON", "BLVD. CUAUTEMOC # 1100 Y L. VICARIO"], 

		["4108", "L PLAZA SAHUARO,SON", "BLVD. SOLIDARIDAD Y AV. TECNOLOGICO"], 

		["4110", "L PLAZA EL VIGIA,SON", "AGUSTIN GARCIA LOPEZ # 1000 NTE."], 

		["4178", "MORELOS,SON.", "PERIFERICO NTE LOC 1 BLVD JM.MORELOS"], 

		["4179", "MIRAMAR,SON.", "CARR. INT. GUAY/HILLO B. LAS VILLAS"], 

		["4180", "MIGUEL ALEMAN,SON.", "MIGUEL ALEMAN 615 NTE LOC 4 ESQ MAYO"], 

		["4192", "CARR HERMOSILLO,SON.", "JUAREZ # 546 /BLVD PORTILLO/MORELOS"], 

		["4242", "L PALO VERDE,SON.", "PERIFERICO PONIENTE # 1085"], 

		["4243", "L HUATABAMPO,SON.", "CARR NAVOJOA Y BAHIA DE QUINO"], 

		["4244", "L EL GRECO,SON.", "CARR INTERNACIONAL KM 4.5"], 

		["4276", "MERCADO DEL SOL,SON", "CZDA. CONST.Y CALLE 2DA AV. GRO 240"], 

		["4297", "SEC PARQUE INDUSTRIAL,SON", "BLVD CIRCUNVALACION Y TORNOS S/N"], 

		["4322", "C.U.M. SON", "BLVD SOLIDARIDAD 599 Y PERIFER.NORTE"], 

		["4331", "V.H. FRONTERA,SON", "CALLE 13"], 

		["4332", "RESIDENCIAS,SON", "AV. REVOLUCION /REVOLUC. Y CALLE 26"], 

		["4356", "IMSS SAN LUIS RIO COLORADO,SON", "AV. LIBERTAD No. 206 ENTRE 2A Y 3A"], 

		["4360", "IMSS CIUDAD OBREGON,SON", "5 DE FEBRERO No. 643 SUR"], 

		["4361", "IMSS HERMOSILLO,SON", "ISIDRO OLVERA S/N"], 

		["4362", "IMSS NOGALES,SON", "CARRETERA INTERNACIONAL KM 6.5"], 

		["4363", "IMSS GUAYMAS,SON", "AV AQUILES SERDAN No.75 LOCAL 7 Y 8"], 

		["4364", "IMSS NANOJOA,SON", "AV. ABASOLO No. 902"], 

		["4365", "IMSS CABORCA,SON", "AV. ALVARO OBREGON No. 185"], 

		["4366", "IMSS AGUA PRIETA,SON", "CALLE 2 S/N ENTRE CALLE 3 Y AV. 19"], 

		["4367", "IMSS NACOZARI,SON", "SUBPACIFICO Y FERROCARRIL S/N"], 

		["4383", "DEL SOL,SON", "BLVD FRANCISCO EUSEBIO KINO 1102"], 

		["4410", "CALIFORNIA,SON", "LOTES 3 AL 8 DE LA MANZANA 2"], 

		["4446", "KALITEA,SON", "BLVD. EL GRECO No. 14"]

	];



var sucTab = 

	[

		["200", "VILLAHERMOSA TAB", "FRANCISCO I MADERO 302 Y 304"], 

		["222", "COMALCALCO TAB", "CALLE JUAREZ 401"], 

		["306", "TENOSIQUE TAB", "CALLE 26 NO. 306"], 

		["318", "EMILIANO ZAPATA TAB", "A. OBREGON ESQ. GREGORIO MENDEZ "], 

		["323", "HUIMANGUILLO TAB", "AV. JUAREZ 124"], 

		["358", "TEAPA TAB", "GREGORIO MENDEZ 102 ESQ. E. BASTAR "], 

		["556", "OLMECA TAB", "PAGES LLERGO 108"], 

		["640", "TAMULTE TAB", "GUSTAVO A ROVIROSA 21 ESQ GREGORIO "], 

		["741", "CIUDAD PEMEX TAB", "1RO.DE MAYO ESQ BLVD LAZARO CARDENAS "], 

		["818", "EUROPLAZA,TAB.", "AV.RUIZ CORTINES S/N ESQ.PERIFERICO "], 

		["4279", "SEC VILLAHERMOSA,TAB.", "SITIO GDE. ESQ CAMPO GIRALDAS(PEMEX) "], 

		["4280", "SEC COMALCALCO 1", "DOM. CONOCIDO (PEMEX COMALCALCO) "], 

		["4282", "SEC DOS BOCAS,TAB", "ZONA INDUSTRIAL"], 

		["4286", "SEC NUEVO PEMEX,TAB", "CARR. LUIS GIL PEREZ S/N"], 

		["4382", "LA CEIBA,TAB", "QUINTIN ARAUZ ESQ.H.COL.MILIT.L23 ZE "], 

		["4459", "SEC CACTUS,TAB", "LA RANCHERA SAN MIGUEL 1a. SECCION "], 

		["4527", "GREGORIO MENDEZ,TABASCO", "GREGORIO MENDEZ 747"]

	];



var sucTam = 

	[

		["7", "ADUANA, TAMPS.", "MENDOZA 1125 SECTOR ADUANA"], 

		["93", "RIO BRAVO TAMPS", "FCO. I. MADERO # 812 PTE."], 

		["139", "NUEVO LAREDO TAMPS", "GUERRERO No 919"], 

		["157", "REYNOSA TAMPS", "JUAREZ 650 NORTE"], 

		["191", "CD MADERO,TAMPS", "1ro DE MAYO No 307 PTE"], 

		["311", "HIDALGO TAMPICO TAMPS", "HIDALGO ESQ FRESNO"], 

		["722", "SOTO LA MARINA TAMPS", "FELIPE DE LA GARZA # 2 NORTE"], 

		["749", "VALLE HERMOSO,TAMPS", "MORELOS Y JOSE GARCIA CARDENAS No.21 "], 

		["860", "VIRREYES (REYNOSA TAMPS)", "AV BLVD HIDALGO ESQ PRAXEDIS BALBOA "], 

		["893", "PLAZA FIESTA TAMPS", "AV PEDRO CARDENAS Y AYUNTAMIENTO 100 "], 

		["920", "JESUS CARRANZA NTE.TAMAULIPAS", "JESUS CARRANZA # 1227 LOCAL 3"], 

		["934", "MORELOS CD.VICTORIA,TAMPS.", "MORELOS # 415"], 

		["935", "ANZALDUAS,REYNOSA TAMPS.", "BLVD. MORELOS Y OAXACA"], 

		["950", "BLVD. LOPEZ MATEOS,TAMPS.", "BLVD. ADOLFO LOPEZ MATEOS # 880 "], 

		["951", "UNIVERSIDAD,TAMPS", "AVE.UNIVERSIDAD 406"], 

		["963", "CURVA TEXAS,TAMPS", "CARR.TAMPICO MANTE 8001"], 

		["972", "REFORMA SUR", "AV. REFORMA SUR 4310-3 Y 15 DE SEPT. "], 

		["982", "LAURO VILLAR,TAMPS.", "AV.LAURO V.KM. 2 GOB. Y REAL DEL V. "], 

		["4066", "G LAREDO MALL,TAMPS.", "BLVD. REF. Y 15 DE SEP. # 4243"], 

		["4067", "G MATAMOROS,TAMPS.", "CALLE PRIMERA Y CANALES"], 

		["4068", "G REYNOSA,TAMPS.", "BLVD. HIDALGO Y PRAXEDIS BALBOA "], 

		["4167", "S EJERCITO,TAMPS.", "EJERCITO NACIONAL /MEX. Y ESTADIO "], 

		["4197", "ALTAMIRA,TAMPS.", "ALLENDE Y OCAMPO S/N CAR.TAMP-MANTE "], 

		["4248", "S CAMPESTRE,TAMPS.", "15 DE SEPTIEMBRE Y REFORMA"], 

		["4249", "S ARBOLEDAS,TAMPS.", "LAURO VILLAR Y LAS ROSAS # 1137 KM 2 "], 

		["4251", "S PLAZA PALMAS,TAMPS.", "BLVD TAMAULIPAS # 2033"], 

		["4256", "SEC TERMINAL MARITIMA PEMEX,TAMPS", "CARRET.DE LA BARRA S/N ENT.PEMEX REF "], 

		["4277", "MIRAMAR,TAMPS.", "TAMAULIPAS ESQ. MONTERREY"], 

		["4316", "PORTES GIL,TAMPS", "PORTES GIL ESQ ESPERANZA"], 

		["4334", "S DEL RIO,TAMPS.", "BLVB. A. VILLAREAL LOCAL 16/B"], 

		["4478", "LAREDO CENTRO,TAMPS", "GUERRERO S/N ESQ.PERU ENT.OCAMPO Y G "], 

		["4479", "TOREO VICTORIA,TAMPS", "CALLE 16 ENTRE CONRADO CASTILLO "], 

		["4522", "ADUANA NUEVO LAREDO,TAMPS", "ARTEAGA ESQ.MENDOZA S/N EDIF.ADUANAL "], 

		["4531", "SEC. COMAPA TAMPICO,TAMPS", "PASEO BELLAVISTA Y EUCALIPTO"]

	];



var sucTlx = 

	[

		["425", "SANTA ANA CHIAUTEMPAN TLAX", "DIAZ VARELA # 12 P.B."], 

		["553", "TLAXCALA TLAX", "PLAZA XICOTENCATL S/N"], 

		["4033", "XICOTENCATL,TLAX", "AV. JUAREZ No. 91"], 

		["4454", "BOULEVARD MADERO,TLAX", "FRANCISCO I. MADERO No. 201 LOCAL D "]

	];



var sucVer = 

	[

		["58", "FORTIN, VER.", "AV. 1 ORIENTE 204"], 

		["89", "AVILA CAMACHO", "AV MANUEL AVILA CAMACHO 243"], 

		["103", "CORDOBA VER", "AV 3 508"], 

		["134", "VERACRUZ VER", "INDEPENDENCIA No 1027"], 

		["169", "COATZACOALCOS VER", "JUAREZ ESQ MORELOS"], 

		["175", "GUTIERREZ ZAMORA VER", "MANUEL AVILA CAMACHO 20"], 

		["177", "PAPANTLA VER", "JUAN ENRIQUEZ 102"], 

		["217", "TIERRA BLANCA VER", "INDEPENDENCIA No 602"], 

		["219", "MINATITLAN VER", "HIDALGO 86"], 

		["247", "TLAPACOYAN VER", "CUAUHTEMOC 300 ESQ FERRER"], 

		["295", "CIUDAD MENDOZA VER", "HIDALGO No 326"], 

		["331", "MARTINEZ DE LA TORRE VER", "AVILA CAMACHO ESQ GUERRERO"], 

		["332", "SAN ANDRES TUXTLA VER", "FRANCISCO I MADERO 4"], 

		["381", "JALTIPAN,VER.", "MORELOS ESQ LEANDRO VALLE S/N"], 

		["397", "LAS CHOAPAS VER", "REVOLUCION 202"], 

		["465", "ISLA VER", "ING.RAUL SANDOVAL 52"], 

		["478", "HUATUSCO,VER.", "AV. 2 PONIENTE No. 316"], 

		["479", "TEMPOAL VER", "AV HIDALGO Y EDUARDO B MARTINEZ "], 

		["485", "REFORMA VER", "CALZ SIMON BOLIVAR No 900"], 

		["604", "CONTINENTAL VERACRUZ", "BLVD.A.RUIZ CORTINEZ 3495 L-1"], 

		["611", "CARDEL", "EMILIANO ZAPATA PTE. # 20"], 

		["619", "PEROTE", "MADERO ENTRE HUMBOLT E HIDALGO"], 

		["655", "BOCA DEL RIO, VER.", "SS JUAN PABLO SEGUNDO # 1555"], 

		["700", "IXTACZOQUITLAN VER", "CARR NACIONAL MEXICO VER KM 320 "], 

		["757", "CANGREJERA VER", "KM 03 CARRETERA A VILLAHERMOSA"], 

		["801", "COSAMALOAPAN VER", "VENUSTIANO CARRANZA ESQ.RUIZ CORTINE "], 

		["804", "J.SIERRA MINATITLAN", "JUSTO SIERRA S/N"], 

		["812", "CIUDAD INDUSTRIAL FRAMBOYAN", "MANZANA 1 LOTE 2-A ZONA COMERCIAL "], 

		["816", "RIO BLANCO VER", "CAMINO NACIONAL # 250"], 

		["879", "ZARAGOZA COATZACOALCOS", "GUERRERO ESQ. ZARAGOZA"], 

		["889", "18 DE MARZO, VER.", "BLVD. A. RUIZ CORTINEZ # 1610"], 

		["938", "ESPA&amp;A,VER.", "AV. ESPA&amp;A # 282-BENTRE WUASH/COLON "], 

		["939", "LAS AMERICAS, VER.", "CTO.COMER.PZA.LAS AMERICAS L.14 Y 15 "], 

		["940", "EMPARAN, VER.", "AV. 5 DE MAYO # 296"], 

		["974", "PLAZA CRISTAL, JALAPA", "CIR.Y A.CHEDRAHUI C.LOC.12,20A24 B "], 

		["4001", "UDAD. DE CARTERA CONTINENTAL,VER.", "BLVD. A. RUIZ CORTINEZ 3495 P.B. "], 

		["4016", "CM JALAPA,VER.", "JALAPA # 279"], 

		["4017", "CM VERACRUZ BOCA DEL RIO,VER.", "AV. S.S. JUAN PABLO SEGUNDO # 48 "], 

		["4181", "PLAZA MUSEO,VER.", "L.B. Y 1RO DE MAYO PZA MUSEO LOC.7/8 "], 

		["4212", "BG COATZACOALCOS,VER", "ZARAGOZA 1107 ESQ PEDRO MORENO"], 

		["4281", "SEC AGUA DULCE 1,VER", "BLVD. AZTECAS S/N (PEMEX DTO. A.D.) "], 

		["4284", "SEC REFINERIA MINA,VER", "SALVADOR DIAZ MIRON S/N"], 

		["4289", "LOS PINOS,VER.", "CARMEN PEREZ # 736-2"], 

		["4290", "PLUVIOSILLA,VER.", "ORIENTE # 6 # 1340 LOC A Y B"], 

		["4310", "UNIDAD DE CARTERA XALAPA,VER", "XALAPE&Ntilde;OS ILUSTRES ESQ ZAMORA "], 

		["4313", "PLAZA TAJIN,VER", "BLVD CARDENAS 807 ESQ MARISCAL SUCRE "], 

		["4314", "PLAZA MANATI,VER", "ANTIGUA CARR A MINATITLAN KM 5 # 1 "], 

		["4326", "FLORESTA,VER", "PROLONGACION DIAZ MIRON KM 1"], 

		["4327", "PLAZA ACUARIO,VER", "BLVD. A. CAMACHO /XICOT. Y PZA ACUAR "], 

		["4486", "SEC PEP POZA RICA,VER", "INT. DEL CAMPO ENTRE BLVD L.CARDENAS "], 

		["4487", "PALMA SOLA,VER", "JUAREZ 21"], 

		["4488", "SEC PEP VERACRUZ", "URANO 420"], 

		["4513", "TERMINAL MARITIMA PAJARITOS,VER", "CARRETERA COATZA-VILLAHERMOSA KM 7.5 "], 

		["4517", "TERMINAL MARITIMA PEMEX TUXPAN", "CARRETERA BARRA NORTE S/N"], 

		["4529", "ADUANA COATZACOALCOS,VER", "RESINTO ADUANAL INTERIOR S/N"], 

		["4812", "ALAMO,VER", "INDEPENDENCIA 174-A"], 

		["4813", "CUITLAHUAC,VER", "AV. 1- 425 ENTRE CALLE 4 Y CALLE 8 "]

	];



var sucYuc = 

	[

		["616", "CHUBURNA YUC", "CALLE 60 NUMERO 277"], 

		["756", "OXKUTZCAB YUC", "CALLE 50 No 105"], 

		["800", "CIUDAD INDUSTRIAL UMAN YUC", "KM 7 1\2 DE LA CARR MERIDA-UMAN "], 

		["909", "PLAZA FIESTA, YUC.", "CALLE 6 No.400 CTO.COM.PLAZA FIESTA "], 

		["910", "CAMPESTRE MERIDA,YUC.", "CALLE 65 NO. 197 LOCALES 31 AL 33 "], 

		["4080", "CHICHEN,YUC", "CALLE 65 ESQ. CON CIRCUITO COLONIAS "], 

		["4081", "ITZAES,YUC", "ITZAES S/N ENTRE CALLE 77 Y 79"], 

		["4285", "CARR. MERIDA,YUC", "CALLE 670 NORTE ESQ. AV XCUMPICH "], 

		["4287", "DONDE,MER.", "CALLE 32 # 200-A LOC. 1,2,3"], 

		["4288", "GRAN PLAZA,MER.", "CALLE 50 DIAG 460 C.COM. LOC. 57 "], 

		["4413", "DORADA MERIDA,YUC", "CALLE 50 No 143 LOC. D, PLAZA DORADA "], 

		["4416", "ALEMAN,YUC", "CALLE 27 No. 180"], 

		["4528", "ADUANA PROGRESO,YUC", "CALLE 32 S/N POR 25 ENTR.MUELLE FISC "]

	];



var sucZac = 

	[

		["33", "NOCHISTLAN,ZAC", "MEJIA No. 10"], 

		["166", "ZACATECAS,ZAC", "HIDALGO Y CALLEJON DE LA BORDADORA "], 

		["607", "LA FLORIDA,ZAC", "BLVD. JOSE LOPEZ PORTILLO # 105 "], 

		["729", "JUCHIPILA,ZAC", "GUADALUPE VICTORIA No. 5 Y 6"], 

		["898", "JEREZ,ZAC", "BIZARRA CAPITAL 27"], 

		["4252", "S ZACATECAS,ZAC", "BLVD. J.L.PORTILLO 1 Y GCIA.SALINAS "], 

		["4422", "S. FRESNILLO,ZAC", "PLATEROS S/N ESQ BLVD PASEO MINERAL "], 

		["4498", "CALERA,ZAC", "5 DE MAYO 207 SUR ENT.OCAMPO Y MADERO"]

	];